breez/breezmobile

- android/app/libs/breez.aar
- lib/bloc/account/account_model.dart
- lib/routes/user/add_funds/add_funds_page.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR sets the right amount allowed for deposit in the add funds page.
> Add funds allowed amount

- lib/bloc/account/account_bloc.dart
- lib/main_pos.dart
- lib/routes/pos/home/pos_home_page.dart
- lib/routes/shared/no_connection_dialog.dart
- lib/routes/user/home/home_page.dart
- lib/services/breez_server/generated/breez.pb.dart
- lib/services/breez_server/generated/breez.pbenum.dart
- lib/services/breez_server/generated/breez.pbgrpc.dart
- lib/services/breez_server/generated/breez.pbjson.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/widgets/error_dialog.dart
> Notify client when lightninglib not started

- android/app/build.gradle
- android/app/libs/breez.aar
- android/app/src/main/java/com/breez/client/BreezApplication.java
- android/app/src/main/java/com/breez/client/workers/ChainSync.java
- pubspec.yaml
This PR integrates WorkManager, changes dependencies accordingly and implement a Worker to sync the chain periodically in the background.
> Background sync

- lib/bloc/account/account_bloc.dart
- lib/main.dart
- lib/main_pos.dart
- lib/routes/pos/transactions/pos_payment_item.dart
- lib/routes/pos/transactions/pos_transactions_page.dart
- lib/routes/user/home/account_page.dart
- lib/routes/user/home/payment_item.dart
- lib/routes/user/home/payments_filter.dart
- lib/utils/date.dart
- lib/widgets/calendar_dialog.dart
I just see "3. Integration into pos and user UI views."
I've integrated some parts into POS that are almost identical.
> Created Calendar Filter dialog and DateUtils

- lib/bloc/account/account_bloc.dart
- lib/routes/pos/transactions/pos_transactions_page.dart
- lib/routes/user/home/account_page.dart
- lib/routes/user/home/payments_filter.dart
- lib/utils/date.dart
- lib/widgets/calendar_dialog.dart
Implemented communication between UI elements for applying filter
Show date filter chips above transaction lists
> Calendar filter ui changes

- .gitignore
- android/app/libs/breez.aar
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/main.dart
- lib/main_pos.dart
- lib/routes/user/home/floating_actions_bar.dart
- lib/routes/user/home/payment_item_avatar.dart
- lib/routes/user/withdraw_funds/withdraw_funds_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/widgets/error_dialog.dart
This PR adds the UI part of the remove funds use case.
> Remove fund

- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/invoice/invoice_model.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
>  Add expiry parameter when creating a POS invoice

- android/app/libs/breez.aar
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/routes/user/get_refund/get_refund_page.dart
- lib/services/breez_server/server.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/services/device.dart
- lib/services/injector.dart
This PR integrate the breez mobile app to the breez library new "Add Funds" API that uses submarine swaps.
> Subswap ui

- android/app/libs/breez.aar
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/routes/user/get_refund/get_refund_page.dart
- lib/routes/user/get_refund/refund_form.dart
- lib/routes/user/get_refund/wait_broadcast_dialog.dart
- lib/routes/user/home/home_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR integrate all the UI for refund submarine swaps addresses.
> Subswap ui integration

- android/app/libs/breez.aar
- lib/bloc/connect_pay/connect_pay_bloc.dart
- lib/bloc/connect_pay/connect_pay_model.dart
- lib/bloc/connect_pay/encryption.dart
- lib/bloc/connect_pay/firebase_session_channel.dart
- lib/bloc/connect_pay/online_status_updater.dart
- lib/bloc/connect_pay/payee_session.dart
- lib/bloc/connect_pay/payer_session.dart
- lib/routes/user/connect_to_pay/connect_to_pay_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/services/deep_links.dart
- lib/services/device.dart
This PR integrates the doubleratchet APi in breez library into the CTP sessions.
> communication based on encrypted state exhcnage

- android/app/libs/breez.aar
- lib/bloc/connect_pay/connect_pay_bloc.dart
- lib/bloc/connect_pay/firebase_session_channel.dart
- lib/bloc/connect_pay/payee_session.dart
- lib/bloc/connect_pay/payer_session.dart
- lib/main.dart
- lib/routes/user/connect_to_pay/connect_to_pay_page.dart
- lib/routes/user/connect_to_pay/payee_session_widget.dart
- lib/routes/user/ctp_join_session_handler.dart
- lib/routes/user/home/home_page.dart
- lib/services/breez_server/generated/breez.pb.dart
- lib/services/breez_server/generated/breez.pbenum.dart
- lib/services/breez_server/generated/breez.pbgrpc.dart
- lib/services/breez_server/generated/breez.pbjson.dart
- lib/services/breez_server/protobuf/breez-client.proto
- lib/services/breez_server/server.dart
- lib/services/breezlib/breez_bridge.dart
This PR contains the client changes to implement mutual notifications during CTP session when one party joins the session.
Also some fixes were made to make the session lifecycle more robust.
> Ctp notifications

- lib/routes/user/pay_nearby/pay_nearby_complete.dart
Prompt user to enable NFC on Pay Someone Nearby page and continue startP2PBeam on return from Settings screen.
> Prompt user to enable NFC on Pay Someone Nearby page

- lib/bloc/connect_pay/payee_session.dart
- lib/bloc/connect_pay/payer_session.dart
- lib/routes/user/connect_to_pay/connected_peer.dart
- lib/routes/user/connect_to_pay/peers_connection.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR uses the breez library ability to attach userInfo to an existing session for caching the other side imageURL and userName.
On reconnecting this information is immediately available for rendering giving a better user experience.
This PR depends on https://github.com/breez/breez/pull/27
> Session state

- android/app/src/main/java/com/breez/client/plugins/breez/backup/BreezBackup.java
- android/app/src/main/java/com/breez/client/plugins/breez/backup/GoogleDriveTasks.java
- lib/bloc/backup/backup_bloc.dart
- lib/routes/shared/initial_walkthrough.dart
- lib/services/backup.dart
- lib/widgets/enable_backup_dialog.dart
This PR refactor the backup/restore code to achive:
1. More readability using synchronous calls rather than task chaining.
2. Fix sign in cancelations.
3. use AsyncTask for backup/restore method calls.
4. separate the Generic google API from the backup specific code into different classes.
> Backup folder rafactor

- android/app/src/main/java/com/breez/client/plugins/breez/backup/BackupConflictException.java
- android/app/src/main/java/com/breez/client/plugins/breez/backup/BreezBackup.java
- android/app/src/main/java/com/breez/client/plugins/breez/backup/GoogleAuthenticator.java
- android/app/src/main/java/com/breez/client/plugins/breez/backup/GoogleDriveTasks.java
- android/app/src/main/java/com/breez/client/plugins/breez/backup/SignInFailedException.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- lib/bloc/account/account_bloc.dart
- lib/bloc/app_blocs.dart
- lib/bloc/backup/backup_bloc.dart
- lib/routes/shared/initial_walkthrough.dart
- lib/routes/shared/no_connection_dialog.dart
- lib/routes/user/home/home_page.dart
- lib/services/backup.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/injector.dart
- lib/widgets/error_dialog.dart
This PR finished the backup process to of breez in google drive.
In addition to previous work that was done, this PR handles node conflicts connected to breez hub.
In such case the nodes are going to drive to determine which has the mandate to continue and which node should be terminated.
In the case the node should be terminated a prompt will be shown that the user must re-install and restore from backup to continue.
> Drive changes

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/breez/client/MainActivity.java
- android/app/src/main/java/com/breez/client/plugins/breez/Permissions.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_permissions_handler.dart
- lib/routes/user/home/home_page.dart
- lib/services/injector.dart
- lib/services/permissions.dart
This PR ask the user to add breez to the "Battery Optimizations exceptions whitelist".
This is a decision we made based on experience with some devices that doesn't respect the WorkManager job running.
The prompt will only happen once before starting lightning lib for the first time.
> Optimization whitelist

- lib/bloc/app_blocs.dart
- lib/bloc/blocs_provider.dart
- lib/main.dart
- lib/main_pos.dart
- lib/pos_app.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/routes/pos/settings/pos_settings_page.dart
- lib/routes/pos/transactions/pos_transactions_page.dart
- lib/user_app.dart
- lib/widgets/navigation_drawer.dart
Refactor of blocs provider to be used to inject state into widgets.
> Blocs provider refactor

- lib/bloc/account/account_model.dart
- lib/routes/user/connect_to_pay/payment_details_form.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR is to use the routingNodeFee to calculate the max allowed amount to pay in CTP session
> Ctp routing fee

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/bloc/invoice/invoice_bloc.dart
- lib/services/breezlib/breez_bridge.dart
- lib/widgets/payment_request_dialog.dart
This PR supports zero amount invoices.
According to the spec it prompts the user to set amount.
> Support zero invoice

- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/ChainSync.java
This PR aligns the java side responsible for scheduling the sync job to the new lightweight job we created at breez library.
https://github.com/breez/breez/pull/38
> implement new ChainSync job using neutrino backend.

- lib/bloc/account/account_model.dart
- lib/bloc/invoice/invoice_bloc.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/routes/shared/dev/dev.dart
- lib/routes/user/home/account_page.dart
- lib/routes/user/home/wallet_dashboard.dart
This PR makes the connection progress bar optional, it also adds settings to control that in the dev screen.
> Optional connect progress

- lib/bloc/account/account_model.dart
- lib/routes/user/home/payment_item.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR implements the necessary UI changes to show fee in the payment list.
Fee will be shown for lightning sent payments that were charged with positive fee only.
> Payment item fee

- lib/routes/user/home/home_page.dart
- pubspec.yaml
Here are the changes to plugin: 
- [Set pasted item as scan result](https://github.com/breez/flutter_barcode_reader/commit/917d8fc54c0cd036cf6da542258985cbf46bcb5f)
- [Change app bars background color to Breez's primary color](https://github.com/breez/flutter_barcode_reader/commit/195cfc877082738ed343ed5036f39597709fdf09)
- [Aligned menu items to start & end, attached their respected icons](https://github.com/breez/flutter_barcode_reader/commit/1773561c26c8eb73a0e3ced1211f129a5b6a8952)
> Implement Paste Invoice to Scan Invoice's view

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/routes/user/home/account_page.dart
- lib/routes/user/home/status_text.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR shows makes sure that in case of breez could not pay the user with the funds in the subswap address, we show a proper error message instead of just "Transferring Funds".
> Add funds error

- lib/bloc/account/account_model.dart
- lib/routes/user/add_funds/add_funds_page.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR changes the message of required reserve in add funds to take the amount dynamically from the AddFundReply response.
The value comes from the server and aligned with the channel reservation for breez channels.
> Chan reserve

- lib/bloc/fastbitcoins/fastbitcoins_bloc.dart
- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/invoice/invoice_model.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/routes/user/create_invoice/create_invoice_page.dart
- lib/services/breezlib/breez_bridge.dart
This PR consolidates the invoice creation in Breez mobile.
Instead of two paths we now have one path that uses the description field to put both text description and custom data.
The format is as follows:
**<Description |
<payee_name> | <payee_url> | <payer_name> | <payer_url>**
> Consolidate invoice

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/routes/user/home/status_indicator.dart
- lib/services/breezlib/progress_downloader.dart
This PR improves the on-boarding user experience by  showing a progress indicator during the bootstrap phase.
> Download progress

- lib/routes/shared/initial_walkthrough.dart
- lib/routes/user/home/beta_warning_dialog.dart
Related issue: https://breeztech.atlassian.net/browse/BU-155
> Show beta warning dialog after pressing let's breez

- lib/routes/user/add_funds/add_funds_page.dart
Fixes: https://breeztech.atlassian.net/browse/BU-154
> Show snackbar at the right location on add funds page

- lib/bloc/account/account_actions.dart
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/bloc/invoice/invoice_bloc.dart
- lib/routes/shared/dev/dev.dart
- lib/routes/user/create_invoice/qr_code_dialog.dart
- lib/routes/user/received_invoice_notification.dart
- lib/services/breezlib/breez_bridge.dart
- lib/widgets/flushbar.dart
- lib/widgets/loader.dart
- lib/widgets/lost_card_dialog.dart
- lib/widgets/payment_failed_report_dialog.dart
- pubspec.yaml
This PR enable the user to agree for uploading payment failures reports so we can analyze the problems and improve his future payment experience.
The main addition is to prompt this dialog after a payment failure, if the user agrees, we will compose a report that consists of the amount, destination, payment request and queryroutes command output and send it to a configured "bug report url".
> Payment failure

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/breez/client/BootReceiver.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/ChainSync.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Notification.java
This PR schedules a periodic job to sync compact filters and check for closed channels while user is offline.
In addition in case of a closed channel detection the user is prompted with a notification and suggested to open the app in order to ensure access to his funds.
> ChannelsWatcher job

- lib/bloc/account/account_actions.dart
- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/routes/shared/account_required_actions.dart
- lib/routes/shared/funds_over_limit_dialog.dart
- lib/routes/user/add_funds/add_funds_page.dart
- lib/routes/user/home/account_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/theme_data.dart
- lib/widgets/loader.dart
This PR implements the changes following https://github.com/breez/breez/pull/71 to show warning icon and dialog in case the user sent funds to the sub swap address were over the limit allowed.
In that case, tapping on the warning icon will trigger a dialog that shows the time when the user can get a refund and when this time has passed the user will be able to refund straight from this screen as well.
> Add funds improvements

- lib/routes/user/marketplace/vendor_webview.dart
- lib/widgets/navigation_drawer.dart
This PR fixes some bug in the marketplace integration.
- Implement the postmessage listener in the plugin itself in both platforms instead of doing it from high level code (https://github.com/breez/flutter_webview_plugin/pull/1)
- Instead of pushing a new "Home" route every time, popping to the existing home is implemented.
- Closing the navigation drawer when clicking on marketplace.
> Marketplace fixes

- lib/routes/user/home/account_page.dart
- lib/routes/user/home/flip_transition.dart
- lib/routes/user/home/home_page.dart
- lib/routes/user/home/payment_item.dart
- lib/routes/user/home/payments_list.dart
- lib/routes/user/home/success_avatar.dart
- lib/routes/user/received_invoice_notification.dart
- lib/widgets/avatar_picker.dart
- lib/widgets/breez_avatar_dialog.dart
- lib/widgets/loading_animated_text.dart
- lib/widgets/payment_request_dialog.dart
Animations are added to payment flow. Issue: [BU-151](https://breeztech.atlassian.net/browse/BU-151)
- Added states to payment request dialog.
- Implemented collapse animation.
- Implemented flip animation.
- Payment request dialog will collapse into payment item on successful payments.
- If payment item is created within last 10 seconds, it will animate flip animation.
- LoadingAnimatedText now uses textStyle parameters style if it's available.
- ~Scroll to top after payment is complete.~
- ~Collapse the dialog to the exact position of first payment item.~
- ~Prevent scroll till collapse animation is complete.~ (is handled by Flutter)
- ~Collapse drawer if it was open before payment process~
> Processing payment animation

- lib/routes/pos/home/pos_invoice.dart
- lib/routes/shared/funds_over_limit_dialog.dart
- lib/routes/user/activate_card/activate_card_page.dart
- lib/routes/user/create_invoice/qr_code_dialog.dart
- lib/routes/user/get_refund/refund_form.dart
- lib/routes/user/get_refund/wait_broadcast_dialog.dart
- lib/routes/user/home/beta_warning_dialog.dart
- lib/routes/user/order_card/order_card_page.dart
- lib/routes/user/withdraw_funds/send_coins_dialog.dart
- lib/routes/user/withdraw_funds/withdraw_funds_page.dart
- lib/widgets/breez_avatar_dialog.dart
- lib/widgets/breez_date_picker.dart
- lib/widgets/calendar_dialog.dart
- lib/widgets/enable_backup_dialog.dart
- lib/widgets/error_dialog.dart
- lib/widgets/lost_card_dialog.dart
- lib/widgets/payment_details_dialog.dart
- lib/widgets/payment_failed_report_dialog.dart
- lib/widgets/restore_dialog.dart
This PR contains changes to all dialog borders and layout of refund form dialog.
> BU-158 | Change all dialogs to round corners

- lib/routes/user/connect_to_pay/payment_details_form.dart
- lib/routes/user/create_invoice/create_invoice_page.dart
- lib/routes/user/pay_nearby/pay_nearby_page.dart
- lib/routes/user/withdraw_funds/send_coins_dialog.dart
- lib/routes/user/withdraw_funds/withdraw_funds_page.dart
- lib/widgets/keyboard_done_action.dart
- lib/widgets/payment_request_info_dialog.dart
This PR fill the gap flutter have in iOS where no "Done" button exists on the virtual keyboard.
Currently we have to add it manually on every numeric field.
> Keyboard actions

- lib/widgets/payment_details_dialog.dart
This PR resolves https://github.com/breez/breezmobile/issues/115
> Change location of Payment Preimage

- lib/routes/user/add_funds/fastbitcoins_page.dart
This PR adds QR Scan button to Voucher Code field on FastBitcoins Redeem Voucher page.
Story: [BU-164](https://breeztech.atlassian.net/browse/BU-164)
Conclusions:
- Barcode scanner plugin should have optional parameters for either of these:
- "Paste Invoice" text
- Showing Paste Invoice button
- "Paste Invoice" should return empty string if the last item on clipboard's text is null
> Add QR scan to Voucher code field in FastBitcoins form

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/bloc/account/account_synchronizer.dart
- lib/routes/shared/account_required_actions.dart
- lib/routes/shared/funds_over_limit_dialog.dart
- lib/routes/user/add_funds/add_funds_page.dart
- lib/routes/user/get_refund/get_refund_page.dart
- lib/routes/user/home/home_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/widgets/link_launcher.dart
This PR follows https://github.com/breez/breez/pull/76 and adapt the UI to the new swap status model.
In addition it adds a link in blockchain explorer and the transaction id of the current in-process submarine swap address so the user can follow it on-chain.
> Detailed onchain status

- lib/routes/pos/home/pos_invoice.dart
- lib/widgets/pos_payment_dialog.dart
- Extract to a separate file and rename from NfcDialog to PosPaymentDialog
- Remove NFC specific code
- Change behaviour so it's not triggered when receiving null on `_readyInvoicesController` stream
> POS: refactor payment dialog

- lib/routes/pos/home/pos_home_page.dart
- lib/routes/shared/initial_walkthrough.dart
- Add syncUI to the POS home page
- Change inital slogan (from spend to earn)
> Pos onboarding

- android/app/src/main/java/com/breez/client/MainActivity.java
- android/app/src/main/java/com/breez/client/plugins/breez/LifecycleEvents.java
- lib/bloc/account/account_bloc.dart
- lib/bloc/app_blocs.dart
- lib/bloc/connect_pay/connect_pay_bloc.dart
- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/user_profile/breez_user_model.dart
- lib/bloc/user_profile/security_model.dart
- lib/bloc/user_profile/user_profile_bloc.dart
- lib/routes/shared/security_pin/security_pin_page.dart
- lib/routes/user/home/home_page.dart
- lib/routes/user/showPinHandler.dart
- lib/services/device.dart
- lib/user_app.dart
This PR adds another optional security layer by adding settings to auto-lock the app when more than a certain interval in the background.
> Auto lock interval

- lib/bloc/account/account_model.dart
- lib/routes/user/home/account_page.dart
- lib/routes/user/home/status_text.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR addds the funding tx link in the pending channel message.
UI now exposes this for users so they can track easily the channel status on chain.
> Expose channel funding tx URL in AccountModel

- lib/routes/user/create_invoice/create_invoice_page.dart
[BU-192](https://breeztech.atlassian.net/browse/BU-192) is addressed in this PR.
On Create Invoice page, clicking on "Receive up to: ..." text will copy the value to amount input.
> Allow copy of amount on Create Invoice page

- lib/routes/shared/security_pin/backup_phrase/backup_phrase_confirmation_page.dart
- lib/routes/shared/security_pin/backup_phrase/generate_backup_phrase_page.dart
- lib/routes/shared/security_pin/backup_phrase/verify_backup_phrase_page.dart
This PR contains improvements to use backup phrase flow.
- The ordering of generated words is changed. It now increases from left to right.
- The layout of the generated words is changed. The number label is aligned to center left and text is centered to the available space.
- At least one item from each page is selected for verification
- Text fields are made compatible with large text scales
> Backup phrase improvements

- lib/routes/user/create_invoice/create_invoice_page.dart
This PR addresses [BU-198](https://breeztech.atlassian.net/browse/BU-198).
Warning text is displayed below create invoice form if there are no errors on account stream.
> Show reserve amount warning on create invoice page

- lib/widgets/send_onchain.dart
This PR addresses [BU-200](https://breeztech.atlassian.net/browse/BU-200?utm_term=&utm_source=jira-slack&utm_medium=referral-external&atlOrigin=eyJpIjoiNjZkYjE0NTE0YzM1NDBlNDkyODdiN2MwZDk1ZDcyNmEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
Hard-coded elements are replaced with theme values and removed the elevation of bottom app bar.
> Apply theme changes to Unexpected Funds dialog

- lib/widgets/calendar_dialog.dart
This PR addresses [BU-199](https://breeztech.atlassian.net/browse/BU-199)
The button size is now stretched according to textScaleFactor.
> Fix date button size on calendar dialog

- lib/routes/user/connect_to_pay/payment_details_form.dart
This PR fixes the scroll on payment details form.
Previously, scroll was not working because of how the layout was built, this caused render issues on specific devices with small screen.
> Payment details form scroll fix

- lib/widgets/breez_dropdown.dart
- lib/widgets/currency_converter_dialog.dart
BreezDropdownButton unfocuses(closes keyboard) and opens the dropdown menu after 400 ms delay.
> Fix bug on DropdownButton when paired with TextField

- lib/main_pos.dart
- lib/pos_app.dart
- lib/routes/pos/home/pos_home_page.dart
- lib/routes/pos/home/pos_invoice.dart
- lib/routes/pos/settings/pos_settings_page.dart
- lib/routes/pos/transactions/pos_transactions_page.dart
- lib/widgets/navigation_drawer.dart
This PR follows up on [BU-189](https://breeztech.atlassian.net/browse/BU-189).
Theme changes are now applied to pos app.
Developers page failed to open because add funds bloc was not initialised on pos_app.dart. It's updated to match user_app.
> Dark theme POS

- lib/bloc/account/account_bloc.dart
- lib/bloc/csv_exporter.dart
- lib/routes/user/home/payments_filter.dart
This PR add logs to ExportPayments flow.
> Add logs to export payments flow

- .gitignore
- lib/bloc/account/account_bloc.dart
- lib/bloc/lnurl/lnurl_actions.dart
- lib/bloc/lnurl/lnurl_bloc.dart
- lib/bloc/lnurl/lnurl_model.dart
- lib/bloc/user_profile/breez_user_model.dart
- lib/bloc/user_profile/user_profile_bloc.dart
- lib/routes/user/create_invoice/create_invoice_page.dart
- lib/routes/user/create_invoice/lnurl_withdraw_dialog.dart
- lib/routes/user/home/home_page.dart
- lib/routes/user/home/invoice_bottom_sheet.dart
- lib/routes/user/lnurl_handler.dart
- lib/services/breez_server/generated/breez.pb.dart
- lib/services/breez_server/generated/breez.pbenum.dart
- lib/services/breez_server/generated/breez.pbgrpc.dart
- lib/services/breez_server/generated/breez.pbjson.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/user_app.dart
- pubspec.yaml
This PR adds the ability to scan lnurl in order to receive.
Also clicking on withdrawal links with a prefix of "lightning:lnurl" now triggers the invoice page enables the user to receive funds.
> Lnurl withdrawal

- lib/routes/user/connect_to_pay/payee_session_widget.dart
- lib/routes/user/create_invoice/create_invoice_page.dart
- lib/routes/user/create_invoice/lnurl_withdraw_dialog.dart
- lib/routes/user/create_invoice/qr_code_dialog.dart
- lib/routes/user/sync_progress_dialog.dart
- lib/routes/user/sync_ui_handler.dart
- lib/widgets/circular_progress.dart
This PR shows a "sync progress" dialog when ever the user creates invoice:
1. create invoice
2. connect to pay
3. lnurl withdraw.
If the user node is not synchronized to the network, the app will show a progress dialog up to the point the node is fully synced and then continue with the original flow.
Since invoices are short expired, this mechanism ensures the user is not in risk.
> trigger sync dialog in create invoice flows.

- lib/bloc/user_profile/user_profile_bloc.dart
This PR follows up on [Add biometrics support ](https://github.com/breez/breezmobile/pull/210), [Update biometrics](https://github.com/breez/breezmobile/pull/223) and fixes issues:
- There's no fingertip menu after activating the pin right after fresh install [BU-208](https://breeztech.atlassian.net/browse/BU-208)
- The fingerprint menu doesn't prompt automatically [BU-209](https://breeztech.atlassian.net/browse/BU-209)
These issues emerged because [this commit](https://github.com/breez/breezmobile/commit/2ab78b5bfa79b17a8e9bb3c9f675dc0004982885#diff-942b641f4ad9455c1856ac3fa442d243) was overlooked during merge.
> Set enrolled biometrics when initializing user

- lib/routes/shared/security_pin/security_pin_page.dart
This PR addresses [BU-205](https://breeztech.atlassian.net/browse/BU-205).
Switch widget -most likely- has an unresolved bug at the moment. I will open an issue to flutter team and take action after their respond. For now, drag gesture is prevented on this specific switch.
The issue: [#46046](https://github.com/flutter/flutter/issues/46046) _(Feel free to simplify the wording...)_
> Prevent drag gesture on biometrics switch

- lib/user_app.dart
- lib/widgets/pin_code_widget.dart
This PR introduces several visual improvements to biometric prompt flow.
- Biometric prompt is shown faster.
- On lockscreen, blank circles are filled to indicate that the fingerprint was entered.
- Lockscreen waits for biometric prompt to disappear before popping.
> Biometric prompt visual improvements

- lib/bloc/user_profile/user_actions.dart
- lib/bloc/user_profile/user_profile_bloc.dart
- lib/routes/user/check_version_handler.dart
- lib/routes/user/home/home_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/widgets/flushbar.dart
This PR check if the client is running the latest version of breez app.
In case not, we show a blocking flushbar that prompt the user to update the app with a direct link to appstore or play store.
> Check version

- lib/routes/user/add_funds/fastbitcoins_page.dart
This PR addresses https://github.com/breez/breezmobile/issues/243
Currency dropdown is now aligned with Voucher Value field.
> Fix misalignment between Voucher Value and Currency dropdown

- lib/routes/user/add_funds/deposit_to_btc_address_page.dart
The content overflowed the available space and was not scroll-able for devices with small screens that use large font sizes.
I wrapped content with scroll view and removed unnecessary code.
> Deposit BTC page accessibility improvement

- lib/routes/marketplace/make_invoice_request.dart
- lib/widgets/payment_confirmation_dialog.dart
- lib/widgets/payment_request_info_dialog.dart
- lib/widgets/processsing_payment_dialog.dart
This PR addresses [POS-31](https://breeztech.atlassian.net/browse/POS-31)
The payeeImageURL was not recognised for certain cases such as a POS invoice. The icon widget is replaced with BreezAvatar so the payeeImageURL is recognised and the proper widget is selected for rendering the icon.
The maxHeight is increased after taking _buildErrorMessage into consideration.
> Payment request dialog icon

- lib/theme_data.dart
- lib/widgets/pos_payment_dialog.dart
This PR addresses [POS-30](https://breeztech.atlassian.net/browse/POS-30)
Payment Approved icon is now white with blue tick on dark mode.
> POS dark mode adjustments

- lib/routes/charge/pos_invoice.dart
- lib/widgets/pos_payment_dialog.dart
In case a POS operator trying to charge when the node is not synchronized we show now a blocking sync progress, same as we do with regular invoice.
> Implement blocking sync on pressing charge.

- ios/Plugins/Breez/BreezLib/NativeMethods.swift
- lib/bloc/lnurl/lnurl_actions.dart
- lib/bloc/lnurl/lnurl_bloc.dart
- lib/bloc/lnurl/lnurl_model.dart
- lib/handlers/lnurl_handler.dart
- lib/routes/home/floating_actions_bar.dart
- lib/routes/sync_progress_dialog.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This PR adds support for opening channel via lnurl.
Users can both scan or click a url in _lnurl_ format to open a channel with an external service provider.
> Lnurl channel

- lib/bloc/pos_catalog/actions.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/bloc/pos_catalog/model.dart
- lib/bloc/pos_catalog/repository.dart
- lib/bloc/pos_catalog/sqlite/db.dart
- lib/bloc/pos_catalog/sqlite/repository.dart
- pubspec.yaml
- test/sqlite_repository_test.dart
This PR implements the Repository layer for the POS catalog implementation.
Currently there is one implementation for sqlite.
All the async actions were added as well and unit tests that covers all CRUD operations.
> Pos product repository

- lib/routes/dev/dev.dart
This PR addresses [BU-220](https://breeztech.atlassian.net/browse/BU-220)
The items below are removed from developers menu.
- Show initial screen
- Show connect progress
- Switch to POS flavor
- Export DB files
The related code is commented-out for future need.
> Remove unnecessary items from Developers menu

- lib/bloc/account/add_funds_bloc.dart
- lib/bloc/account/fiat_conversion.dart
- lib/bloc/pos_catalog/actions.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/bloc/pos_catalog/model.dart
- lib/bloc/user_profile/currency.dart
- lib/routes/charge/currency_wrapper.dart
- lib/routes/charge/items/catalog_item.dart
- lib/routes/charge/items/create_item.dart
- lib/routes/charge/items/items_list.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/sale_view.dart
- lib/routes/dev/dev.dart
- lib/routes/home/floating_actions_bar.dart
- lib/routes/home/wallet_dashboard.dart
- lib/widgets/back_button.dart
- lib/widgets/badge.dart
- pubspec.yaml
This PR adds initial implementation of Sale view applied in the POS mode.
> Sales view

- lib/bloc/account/fiat_conversion.dart
- lib/bloc/app_blocs.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/bloc/pos_catalog/model.dart
- lib/bloc/user_profile/currency.dart
- lib/routes/charge/currency_wrapper.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/sale_view.dart
This PR fixes the wrong offset sometimes seen in the sale total charge. There were two issues that have been caused this weird behavior:
1. The conversion to sats and backwards wasn't accurate enough and lost precision.
2. The rates were changing and the sales view was not updated accordingly.
> Consider dynamic fee changes on sale charge.

- lib/bloc/pos_catalog/model.dart
- lib/routes/charge/pos_invoice.dart
This PR shows the current pending amount in POS as custom item in the current sale.
Before user needed to enter "+" in order for it to be counted.
In order to implement it we now hold a pendingSaleLine at the pos_invoice page. The "+" only clears the current pending amount by setting this variable to null.
> Pending sale line

- lib/routes/add_funds/fastbitcoins_page.dart
- lib/routes/charge/items/item_page.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/order_card/order_card_page.dart
- lib/routes/pay_nearby/pay_nearby_page.dart
- lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart
- lib/routes/security_pin/backup_phrase/enter_backup_phrase_page.dart
- lib/routes/security_pin/backup_phrase/generate_backup_phrase_page.dart
- lib/routes/security_pin/backup_phrase/verify_backup_phrase_page.dart
- lib/routes/withdraw_funds/reverse_swap_confirmation.dart
- lib/routes/withdraw_funds/sweep_all_coins_confirmation.dart
- lib/widgets/single_button_bottom_bar.dart
This PR addresses [POS-63](https://breeztech.atlassian.net/browse/POS-63) and [POS-51](https://breeztech.atlassian.net/browse/POS-51)
- 'Item' text is removed from input fields.
- Submit buttons text is now in uppercase.
- Currency dropdown is aligned with price text !!!requires testing!!!
Note:
Button font was not different than similar buttons in the app. The only difference was capitalization. Same widget, SingleButtonBottomBar, is being used for bottom bar buttons across the app.
> Add items review

- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/pos_catalog/actions.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/bloc/pos_catalog/model.dart
- lib/bloc/pos_catalog/repository.dart
- lib/bloc/pos_catalog/sqlite/db.dart
- lib/bloc/pos_catalog/sqlite/repository.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/sale_view.dart
- lib/routes/transactions/pos_payment_item.dart
- lib/routes/transactions/pos_transactions_page.dart
- test/sqlite_repository_test.dart
This PR connects a sale to its invoice. We add another field to the Sale (paymentHash) which reflects the payment hash at the invoice that was generated.
We can fetch a sale by the hash and show the corresponding read-only sale view when transaction details are requested.
> Connect sale to payment

- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/sale_view.dart
- lib/routes/transactions/pos_payment_item.dart
This PR adds the price conversion to the current sale currency for every sale line.
In case the Sale is read-only (executed sale) we show the conversion to Sats.
> Sale currency

- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/pos_payment_dialog.dart
- lib/routes/charge/sale_view.dart
- lib/routes/charge/succesfull_payment.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/create_invoice/lnurl_withdraw_dialog.dart
- lib/routes/create_invoice/qr_code_dialog.dart
- lib/widgets/practicles_animations.dart
- pubspec.yaml
This PR adds an animated effect on successful payments.
Some changes in files layout was needed.
> Payment animation

- lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart
> Small typo

- lib/routes/charge/items/item_avatar.dart
- lib/routes/charge/items/item_avatar_picker.dart
- lib/routes/charge/items/item_page.dart
- lib/utils/icon_map.dart
This PR follows up on #318 and addresses [POS-83]( https://breeztech.atlassian.net/browse/POS-83)
> Item avatar picker fixes

- lib/bloc/pos_catalog/model.dart
- lib/bloc/pos_catalog/sqlite/db.dart
This PR adds the missing item_id field to the sale_line table.
> Adding missing item_id field.

- lib/routes/home/status_text.dart
> Simple grammar fix

- lib/routes/home/floating_actions_bar.dart
- lib/routes/home/invoice_bottom_sheet.dart
- lib/widgets/barcode_scanner_placeholder.dart
This PR addresses [BU-222](https://breeztech.atlassian.net/browse/BU-222)
> Node ID(pub key) support to QR Scan

- android/app/build.gradle
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/ChainSync.java
- ios/Plugins/Breez/BreezLib/NativeMethods.swift
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/graph_downloader.dart
- pubspec.yaml
This PR implements the client side of the local graph sync feature.
It adds the ability to download a file that contains the graph data and synchronize its local channeldb graph with it.
The heuristic on whether to download or not is implemented in breez library and this PR is responsible for the downloading job and calling the right endpoint in breez.
For the purpose of testing how this affect startup and bootstrap the code right now synchronize the graph on every startup.
> Graph sync from file.

- android/app/src/main/java/com/breez/client/MainActivity.java
- lib/bloc/lnurl/lnurl_bloc.dart
- lib/handlers/lnurl_handler.dart
- lib/routes/home/floating_actions_bar.dart
- lib/services/nfc.dart
Show a loader while lnlink is being handled, much like receiving an invoice.
> Create loader on receiving lnlink via NFC

- lib/routes/add_funds/fastbitcoins_page.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/home/floating_actions_bar.dart
- lib/routes/home/invoice_bottom_sheet.dart
- lib/routes/withdraw_funds/withdraw_funds_page.dart
- lib/utils/qr_scan.dart
- lib/widgets/send_onchain.dart
- pubspec.yaml
This PR allows users to select a QR code image from their gallery through flutter_barcode_reader plugin.
> Decode QR code from gallery images

- lib/widgets/barcode_scanner_placeholder.dart
Paste Invoice button is replaced with back button on BarcodeScannerPlaceholder page.
> Replace paste invoice button with back button

- lib/home_page.dart
- lib/routes/home/floating_actions_bar.dart
- lib/widgets/enter_payment_info_dialog.dart
This PR addresses [BU-242](https://breeztech.atlassian.net/browse/BU-242)
Paste Invoice or Node ID button is enabled even if there's no valid clipboard data.
It's past behaviour is being kept and takes priority but when there's no valid clipboard data, an input dialog pops up, prompting user to enter a invoice or node id.
> Always enable 'Paste Invoice or Node ID'

- lib/bloc/invoice/invoice_bloc.dart
- lib/bloc/invoice/invoice_model.dart
- lib/home_page.dart
- lib/routes/home/floating_actions_bar.dart
Clicking "Paste Invoice or Node ID" with our payments in clipboard did nothing as it was getting filtered out in invoice bloc.
The payment is filtered out before the invoice is added to decodeInvoice sink and if it's recognized as our own, enter payment info dialog shows up.
> Open input dialog for our payments in clipboard

- lib/routes/add_funds/deposit_to_btc_address_page.dart
- lib/theme_data.dart
Warning text box and warning texts style is matched with designs on [page #3 and 4#](https://www.figma.com/proto/pNMrKD37uR7aklFrcInird/Breez?node-id=165%3A10402&scaling=scale-down)
> Warning text ui update

- lib/home_page.dart
- lib/routes/home/account_page.dart
- lib/routes/home/bottom_actions_bar.dart
- lib/routes/home/qr_action_button.dart
- lib/theme_data.dart
FloatingActionsBar is replaced with the new design on: https://www.figma.com/proto/pNMrKD37uR7aklFrcInird/Breez?node-id=102%3A9911&scaling=scale-down
> Bottom app bar

- lib/routes/home/wallet_dashboard.dart
- lib/theme_data.dart
Wallet dashboard is replaced with new design on: https://www.figma.com/file/pNMrKD37uR7aklFrcInird/Breez?node-id=102%3A9871
Long press action is removed, fiat conversion will be shown below balance.
> Wallet dashboard

- lib/routes/initial_walkthrough.dart
- lib/routes/splash_page.dart
- lib/theme_data.dart
- lib/widgets/navigation_drawer.dart
This PR addresses [BU-262](https://breeztech.atlassian.net/browse/BU-262).
Removed waves images from splash, intro page and sidebar.
Applied new sidebar colors and style.
> Sidebar changes and removal of waves images

- lib/routes/create_invoice/qr_code_dialog.dart
This PR addresses flicker issue on invoice dialog when it's loading.
The loader containers height is increased and it now crossfades to qr code image.
> Invoice dialog flickering on load

- lib/routes/home/qr_action_button.dart
- lib/utils/lnurl.dart
This PR is the small addition needed for https://github.com/breez/breez/pull/127
and closes #381 
Thanks @fiatjaf
> Support lnurl fallback.

- ios/Plugins/Breez/BreezLib/NativeMethods.swift
- lib/bloc/lnurl/lnurl_actions.dart
- lib/bloc/lnurl/lnurl_bloc.dart
- lib/bloc/lnurl/lnurl_model.dart
- lib/handlers/lnurl_handler.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbjson.dart
This is the UI side of lnurl auth implementation. It is a continue to: https://github.com/breez/breez/pull/130
> Lnurl auth

- lib/bloc/user_profile/breez_user_model.dart
- lib/bloc/user_profile/business_adress.dart
- lib/routes/settings/pos_settings_page.dart
Business Address consisting of two lines is added to BreezUserModel and can be changed under POS Settings.
> Add Business address to POS Settings

- lib/bloc/user_profile/breez_user_model.dart
- lib/routes/home/account_page.dart
- lib/routes/home/wallet_dashboard.dart
This PR addresses [BU-268](https://breeztech.atlassian.net/browse/BU-268)
Users will toggle privacy mode when they reach end of currency list and their balance will be hidden.
The app currency will be sats(tx list, invoice).
> Add privacy mode for balance

- lib/routes/funds_over_limit_dialog.dart
- lib/routes/pending_closed_channel_dialog.dart
- lib/widgets/backup_provider_selection_dialog.dart
Only the affected titles are changed.
> Fix dialog titles on devices with large text size settings

- lib/routes/podcast/theme.dart
This PR addresses [BU-273](https://breeztech.atlassian.net/browse/BU-273)
Created Breez themes for Anytime Plugin using and [modifying](https://github.com/breez/anytime_podcast_player/pull/2)  the theme specifications of Anytime plugin.
> Apply Breez theme Anytime plugin

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Runner.entitlements
- lib/handlers/podcast_url_handler.dart
- lib/home_page.dart
- lib/main.dart
- lib/routes/podcast/podcast_page.dart
- lib/routes/podcast/share_episode_button.dart
- lib/routes/podcast/share_podcast_button.dart
- lib/services/deep_links.dart
- pubspec.yaml
This PR addresses [BU-321](https://breeztech.atlassian.net/browse/BU-321)
Users will be able to share podcasts via share button that's added to every podcasts detail page.
Clicking this share button will create a Firebase dynamic link that has feedURL info of the podcast. This link will use the existing deeplink entry point for C2P links.
> Add ability to share podcasts

- lib/bloc/fastbitcoins/fastbitcoins_bloc.dart
- lib/services/injector.dart
- pubspec.yaml
- test/fastbitcoins_bloc_test.dart
- test/mocks.dart
- test/sqlite_repository_test.dart
I have been studying the project and I notice the tests through the `flutter test` are not passing, at least not in my machine.
I manage to make the tests pass with those changes.
Please let me know if something I did should not be made or be maybe in another way.
> Make tests pass again 💪 🚀

- .gitignore
- test/sqlite_repository_test.dart
> Increase test coverage of sqlite/repository from 81% to 100%

- lib/bloc/app_blocs.dart
- lib/bloc/fastbitcoins/fastbitcoins_bloc.dart
- test/bloc_tester.dart
- test/fastbitcoins_bloc_test.dart
Increase test coverage of `fastbitcoins` group from 76% to 100%
> Increase test coverage of fastbitcoins from 76% to 100%

- android/app/src/main/java/com/breez/client/MainActivity.java
Based on https://github.com/breez/breezmobile/issues/184 suggestion
https://user-images.githubusercontent.com/1225438/122447037-b1729100-cf79-11eb-993f-f6662fe7300e.mp4
https://user-images.githubusercontent.com/1225438/122447048-b46d8180-cf79-11eb-98eb-f6373817e16c.mp4|
> Add secure flag to main activity

- lib/bloc/user_profile/currency.dart
- lib/widgets/amount_form_field.dart
- test/bloc/user_profile/currency_test.dart
- test/widgets/amount_form_field_test.dart
Based on https://github.com/breez/breezmobile/issues/170 suggestion 
https://user-images.githubusercontent.com/1225438/122422829-d956fa00-cf63-11eb-9951-f5aed9faab09.mp4
> Add satoshi amount form formatter for amount form field

- lib/home_page.dart
- lib/routes/security_pin/lock_screen.dart
- lib/widgets/close_popup.dart
I did apply the suggestion of this thread https://github.com/breez/breezmobile/issues/186
https://user-images.githubusercontent.com/1225438/122470520-88132e80-cf94-11eb-9317-bc5afca4d7ee.mp4
https://user-images.githubusercontent.com/1225438/122470545-8e090f80-cf94-11eb-8076-00823a811a79.mp4
> Add close confirmation popup on lock screen

- lib/widgets/error_dialog.dart
Fix the issue https://github.com/breez/breezmobile/issues/448
https://user-images.githubusercontent.com/1225438/123283362-b6879100-d4e1-11eb-951b-ceb46de7bddf.mp4
> Make close popup dismissible

- lib/bloc/podcast_payments/podcast_payments_bloc.dart
I'm not sure if static strings are allowed here.  Since it's unlikely for the app name to change, maybe this is ok?
> add app_name to tlv record - addresses #519

- lib/bloc/backup/backup_bloc.dart
- lib/routes/initial_walkthrough.dart
- lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart
- lib/routes/security_pin/backup_phrase/enter_backup_phrase_page.dart
- lib/routes/security_pin/backup_phrase/generate_backup_phrase_page.dart
- lib/routes/security_pin/backup_phrase/verify_backup_phrase_page.dart
This PR addresses [BU-348](https://breeztech.atlassian.net/browse/BU-348)(#489)
Future backup phrases will consist of 12 words down from 24 however existing 24 word backup phrases will continue to be supported on restoration process.
> Reduce excessive encryption key length

- ios/Runner.xcodeproj/project.pbxproj
This fix is dependent on https://github.com/breez/breez/pull/136
> Fix for Issue #522: "No such module bindings".

- lib/routes/home/account_page.dart
- lib/routes/home/payment_item.dart
- lib/routes/home/payments_list.dart
Implements https://github.com/breez/breezmobile/issues/446 suggestion
It does not hide the number on the message, to do it is necessary some kind of Intelligence on the text. 
how it looks like:
https://user-images.githubusercontent.com/1225438/126006092-7ac487b0-44e9-4258-988b-a7cacbb7e192.mp4
> Hide amount on transaction list when user hide balance flag is on

- lib/bloc/lnurl/lnurl_bloc.dart
Fix the issue https://github.com/breez/breezmobile/issues/511
In the following screen record I did: invalid clipboards, repeated clipboards and valid clipboard, it seems to be working.
I did not record but I did test the camera flow and it looks to be working, it is because I move the private `_handleLNUrl` to `lib/utils/lnurl.dart` as a public function to be reused by the home.
https://user-images.githubusercontent.com/1225438/125650306-5b78fa8e-04cc-4aee-9804-e972c7a33dea.mp4
> Load lnurl from clipboard automatically

- lib/bloc/lnurl/lnurl_model.dart
- lib/routes/lnurl_fetch_invoice_page.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbgrpc.dart
- lib/services/breezlib/data/rpc.pbjson.dart
Depends on <https://github.com/breez/breez/pull/138>.
> LNUrl-Pay: Use CommentAllowed.

- lib/routes/lnurl_fetch_invoice_page.dart
> Prefill amount in LNURL Pay if it's unambiguous

- lib/bloc/podcast_payments/actions.dart
- lib/bloc/podcast_payments/podcast_payments_bloc.dart
- lib/routes/podcast/boost.dart
- lib/routes/podcast/boost_message_dialog.dart
- lib/routes/podcast/payment_adjustment.dart
This PR addresses #524
Long pressing boost button will now open an input dialog for users to attach message to their boosts.
> Add boost message on long pressing boost message

- lib/bloc/lnurl/lnurl_bloc.dart
- lib/bloc/lnurl/lnurl_model.dart
- lib/routes/lnurl_fetch_invoice_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/utils/lnurl.dart
This PR depends on https://github.com/breez/breez/pull/140 .
> Lightning-Address (sending)

- lib/routes/home/payment_item.dart
- lib/widgets/payment_details_dialog.dart
> Improve lightning-address ui elements.

- lib/routes/home/qr_action_button.dart
When the user scan a url link, the app offers the possibility to open it with the device's browser.
https://user-images.githubusercontent.com/1225438/132504564-281c99b3-114a-430e-99cb-2d43c6eb94db.mp4
> Add support to web links opening on external browser

- lib/routes/podcast/boost.dart
- lib/routes/podcast/boost_message_dialog.dart
- lib/routes/podcast/custom_amount_dialog.dart
- lib/routes/podcast/custom_amount_form.dart
Minor adjustments:
- Show the current amount value on boostagram dialog but shows nothing on custom amount dialog
- Minor label/text changes
> Minor boostagram adjustments

- lib/widgets/pin_code_widget.dart
The pin widget was not showing some numbers on small screens, this PR fixes it.
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/133800528-00f4e2e8-1989-4576-bdc8-244fd04b304b.jpg)|![after](https://user-images.githubusercontent.com/1225438/133800525-a45686ee-1f41-4017-b911-63f6d67d490a.jpg)|
Other scenarios:
|small but no so small|error messsage|entire/big screen|unlock screen|
|![small but no so small](https://user-images.githubusercontent.com/1225438/133800668-fc9a6614-ffa4-49a1-aa7b-5877528535b2.jpg)|![error messsage](https://user-images.githubusercontent.com/1225438/133800666-1bfd664c-da8a-4eb2-b676-ed0389b48cdc.png)|![entire screen](https://user-images.githubusercontent.com/1225438/133800658-81175b79-c5ad-4c7c-97be-df746f42f4d9.pn …
> Fix pin widget on small screens

- lib/bloc/account/account_model.dart
- lib/utils/date.dart
- lib/widgets/breez_avatar.dart
|Item list|Dialog|
|---|---|
|![Screenshot_20211027-103854_Breez_Debug](https://user-images.githubusercontent.com/1225438/139081382-8f13dbe2-833b-4f65-9321-e8d37e1a2e26.png)|![Screenshot_20211027-103934_Breez_Debug](https://user-images.githubusercontent.com/1225438/139081392-b55f4391-7978-4863-aa90-833267539736.png)|
|![Screenshot_20211027-104035_Breez_Debug](https://user-images.githubusercontent.com/1225438/139081397-937ff0b4-f372-492d-88b5-c5da7d6b2e60.png)|![Screenshot_20211027-104048_Breez_Debug](https://user-images.githubusercontent.com/1225438/139081400-5150de78-9b09-4794-8477-fd53ba0dfc46.png)|
> Add sale icon and title to POS sale items

- src/json/currencies.json
|Before|After|
|---|---|
|![Before](https://user-images.githubusercontent.com/1225438/139668260-bbd3ab9c-9dc6-43a9-bbe3-47b7a2690665.png)|![After](https://user-images.githubusercontent.com/1225438/139668268-c27edda4-503f-41f9-baef-bc0f592063e2.png)|
Fixes https://github.com/breez/breezmobile/issues/598
> Fix polish currency

- lib/bloc/account/account_model.dart
Notice the first item, it is not a sale, fixed the identification on this PR
|Before|After|
|---|---|
|![Before](https://user-images.githubusercontent.com/1225438/139680079-d5c7ffec-b8f3-4a47-8bde-0e5c1a9acf42.png)|![After](https://user-images.githubusercontent.com/1225438/139680083-371dbb1f-775b-4888-a360-b3f43226508b.png)|
> Fix Payment Vendor Breez identification for sale items

- lib/bloc/podcast_payments/podcast_payments_bloc.dart
This will need review.  I'm not a Dart guy.
Two of the property types didn't match the spec defined at:
https://github.com/satoshisstream/satoshis.stream/blob/main/TLV_registry.md#field-7629169
> Fix type errors in tlv json - #624

- lib/bloc/account/add_fund_vendor_model.dart
- lib/bloc/account/add_funds_bloc.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_pt.arb
- lib/l10n/text_uri.dart
- lib/routes/home/bottom_actions_bar.dart
|English|Portuguese|Spanish|
|---|---|---|
|![eg_home](https://user-images.githubusercontent.com/1225438/142264094-3fa6787f-e39c-4095-9b8d-7202f540d694.png)|![pt_home](https://user-images.githubusercontent.com/1225438/142264100-52469345-d8ae-47c6-bbec-09b7e09dbb70.png)|![sp_home](https://user-images.githubusercontent.com/1225438/142264104-d24947dc-210e-4346-943a-935bbe7dd083.png)|
|![eg_send](https://user-images.githubusercontent.com/1225438/142264083-f6d4aa9a-dc73-4559-83fb-43e11830912c.png)|![pt_send](https://user-images.githubusercontent.com/1225438/142264097-ff127187-d212-4fa7-8cfa-9e1ed3527c76.png)|![sp_send](https://user-images.githubusercontent.com/1225438/142264108-cb3757d4-fedb-4181-93b3-d3cbff3c4ff4.png)|
|![eg_receive](https://user-images.githubusercontent.com/1225438/142264092- …
> Add translations for home bottom action bar

- ios/Runner/Info.plist
- lib/l10n/app_fi.arb
- lib/l10n/fi_messages.dart
- lib/l10n/locales.dart
- lib/utils/date.dart
Thank you very much @tlindi for the Finnish translations.
P.S. The time ago messages will be pushed to the timego library and removed from here as soon as they accept the translations
> Add Finnish translation, thank you @tlindi

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_pt.arb
- lib/widgets/payment_details_dialog.dart
Add translation to payment detail dialogs
|English|Spanish|Portuguese|
|---|---|---|
|![1_en](https://user-images.githubusercontent.com/1225438/143463978-24849957-c1c3-4368-ba6d-78de5ea537d4.png)|![1_es](https://user-images.githubusercontent.com/1225438/143463985-32c88dc5-e2a5-4a0d-93e7-7a8dd9018e1f.png)|![1_pt](https://user-images.githubusercontent.com/1225438/143463986-b303e8be-41a4-46d3-9752-49ca9d9e52a1.png)|
|![2_en](https://user-images.githubusercontent.com/1225438/143463988-3c275ba6-fe58-46b6-b119-287e2e2b826f.png)|![2_es](https://user-images.githubusercontent.com/1225438/143463992-933def7b-78bb-4d51-be15-8a194918e4c5.png)|![2_pt](https://user-images.githubusercontent.com/1225438/143463994-a64047a5-d0f9-4495-85fa-92ef7976df78.png)| …
> Add payment details dialog translations for pt and es

- lib/bloc/pos_catalog/actions.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/routes/charge/pos_invoice.dart
Fixes https://github.com/breez/breezmobile/issues/635
https://user-images.githubusercontent.com/1225438/143877835-073a516b-4e8e-4d8f-8995-551195347628.mp4
> Remember last selected tab on PoS

- lib/routes/home/qr_action_button.dart
Some valid URLs read from the QR code did not open on newer androids, I'm fixing it on this PR.
> Improve URL handling on URLs read from QR code

- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
Thanks to @tlindi for the Finnish translations
Thanks to @bitcoinuser for the Portuguese improvements
> Add Finnish translations and improve some Portuguese translations

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/charge/items/item_page.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/pos_invoice_cart_bar.dart
- lib/routes/charge/pos_invoice_items_view.dart
- lib/routes/charge/pos_invoice_num_pad.dart
Thanks to @tlindi for the Finnish translations
|English|Spanish|Finnish|Portuguese|
|![en](https://user-images.githubusercontent.com/1225438/146592332-d8243e5a-78a6-44be-b6c2-6d06a7fcf601.png)|![es](https://user-images.githubusercontent.com/1225438/146592339-3207fb5c-c782-4a74-912b-cb9725677e86.png)|![fi](https://user-images.githubusercontent.com/1225438/146592341-c6636c9a-f4a7-4ced-a6af-28ad6498dd4e.png)|![pt](https://user-images.githubusercontent.com/1225438/146592342-be20e7f1-cc58-4f61-983c-c7d5e23ffdd7.png)|
P.S. The POS page build method was a little bit dense and big so I break it on several methods and more pages.
> Translate texts on POS page

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_pt.arb
- lib/routes/home/payments_filter.dart
- lib/routes/transactions/pos_payment_item.dart
- lib/routes/transactions/pos_transactions_page.dart
- lib/widgets/calendar_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/147151197-9ee271d3-4050-4a0e-96c8-8de25f921f05.png)|![es](https://user-images.githubusercontent.com/1225438/147151204-11470626-e9cc-418f-8020-9584ae962b50.png)|![pt](https://user-images.githubusercontent.com/1225438/147151208-1fd7a7e1-a944-4928-9c96-08ea7e696bb4.png)|
> Translate transactions page

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/home/payments_filter.dart
|English|Spanish|Portuguese|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/147492890-69dab62e-3d65-4a81-a33c-7aa8c938c3f1.png)|![es](https://user-images.githubusercontent.com/1225438/147492891-dd6e0564-d8ee-43e6-8e30-efa95f16c9fc.png)|![pt](https://user-images.githubusercontent.com/1225438/147492892-0a9930ab-d20e-4934-989c-265833bf937d.png)|
> Add translations to payment filter

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/fiat_currencies/fiat_currency_settings.dart
It is missing the translation for the currencies, adding on the next PR
> Add translation for fiat currencies page

- lib/routes/podcast/boost.dart
- lib/routes/podcast/share_episode_button.dart
- lib/routes/podcast/share_podcast_button.dart
- lib/routes/podcast/speed_selector.dart
- lib/routes/podcast/theme.dart
- lib/routes/podcast/transport_controls.dart
- pubspec.yaml
This PR addresses [BU-395](https://breeztech.atlassian.net/browse/BU-395), [BU-396](https://breeztech.atlassian.net/browse/BU-396) and [BU-397](https://breeztech.atlassian.net/browse/BU-397).
Deprecated theme values are updated for podcast theme and placeholder widgets.
Speed Selector widget is updated.
> Update deprecated theme values and Speed Selector widget

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/enter_payment_info_dialog.dart
|Language|Light|Dark|
|---|---|---|
|English|![en_light](https://user-images.githubusercontent.com/1225438/147671566-59c8547d-0e03-4c9b-b4bd-479dba08b26b.png)|![en_dark](https://user-images.githubusercontent.com/1225438/147671569-8128e10b-5d88-46d0-9927-f6c35f227e72.png)|
|Portuguese|![pt_light](https://user-images.githubusercontent.com/1225438/147671556-f7539f8c-8901-4afc-bc5c-2e75b65756df.png)|![pt_dark](https://user-images.githubusercontent.com/1225438/147671559-0057950e-8267-4c27-81f2-8cdcc02a861e.png)|
|Espanish|![es_light](https://user-images.githubusercontent.com/1225438/147671560-c41bedb8-305b-4582-8c1e-1a0e1f20192d.png)|![es_dark](https://user-images.githubusercontent.com/1225438/147671562-f7592b99-d35c-4a61-8395-94b794c40092.png)|
> Add translation to payee information box, add a disclaimer to the input field

- lib/bloc/connect_pay/payee_session.dart
- lib/bloc/connect_pay/payer_session.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/connect_to_pay/connect_to_pay_page.dart
- lib/routes/connect_to_pay/payee_session_widget.dart
- lib/routes/connect_to_pay/payer_session_widget.dart
- lib/routes/connect_to_pay/payment_details_form.dart
- lib/routes/connect_to_pay/peers_connection.dart
- lib/routes/connect_to_pay/session_instructions.dart
- lib/widgets/delay_render.dart
|English|Espanish|Portuguese|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/147773984-c1caa162-3d96-457c-835b-5b3ed0bb1558.png)|![es_1](https://user-images.githubusercontent.com/1225438/147774000-662ef322-84f4-4dc2-8dfb-9abe03741a5f.png)|![pt_1](https://user-images.githubusercontent.com/1225438/147774019-767801d8-d555-41f8-bffe-8e8b21b57088.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/147773985-089e821f-8676-4cb3-9380-dfebbc1e487e.png)|![es_2](https://user-images.githubusercontent.com/1225438/147774001-3d3492e3-8917-49d2-aeac-b4c54187ac9a.png)|![pt_2](https://user-images.githubusercontent.com/1225438/147774021-a598ba2a-837f-41e4-ac91-5137d2c2a310.png)|
|![en_3](https://user-images.githubusercontent.com/1225438/147773986-f6ba …
> Translate connect to pay flow (En, Es, Pt)

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/l10n/finnish_implements_duration_locale.dart
- lib/routes/security_pin/security_pin_page.dart
It is necessary to translate the biometrics options yet, I'll make a separated PR for it as that can have some side effects
|Lang|No Pin|With Pin|
|---|---|---|
|En|![en_no_pin](https://user-images.githubusercontent.com/1225438/148081131-d5c0c2b7-ce7b-4dd0-ba0c-6c53fd85a2f3.png)|![en_pin](https://user-images.githubusercontent.com/1225438/148081140-18b91b4b-5721-4ced-af76-418ffbfa2895.png)|
|Es|![es_no_pin](https://user-images.githubusercontent.com/1225438/148081144-c5178bd5-99a4-4fec-9fe5-2fc63de8d2c3.png)|![es_pin](https://user-images.githubusercontent.com/1225438/148081147-b8866a7b-b743-445e-a0ca-4d6fa4f00485.png)|
|Pt|![pt_no_pin](https://user-images.githubusercontent.com/1225438/148081149-30a78dbf-cc45-402e-9509-38fb3b183846.png)|![pt_pin](https://user-images.githubusercontent.com/1225 …
> Translate security & backup screen

- lib/bloc/user_profile/user_profile_bloc.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/security_pin/security_pin_page.dart
- lib/services/local_auth_service.dart
- lib/widgets/pin_code_widget.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/148107830-7f6fb362-882e-4f03-97cb-499c1730dad7.png)|![es](https://user-images.githubusercontent.com/1225438/148107837-1113add0-64e3-4305-b6ed-465467c0861c.png)|![pt](https://user-images.githubusercontent.com/1225438/148107839-9380e91d-2766-4dd4-9b34-09f8659a33bc.png)|
> Translate security options

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/security_pin/change_pin_code.dart
|Language|Pin code|Re-enter|Error|
|En|![en_1](https://user-images.githubusercontent.com/1225438/148114539-e27766ba-843d-48c6-a6fb-a1a99f77d50c.png)|![en_2](https://user-images.githubusercontent.com/1225438/148114550-19d94701-dd67-4dc9-8127-f9e44e17a32e.png)|![en_3](https://user-images.githubusercontent.com/1225438/148114552-9c64330b-ff01-4f20-bd22-ec637674e952.png)|
|Es|![es_1](https://user-images.githubusercontent.com/1225438/148114554-af142d82-e4e9-4e7f-817b-ec745e1cf84e.png)|![es_2](https://user-images.githubusercontent.com/1225438/148114556-61987bcb-37d7-465d-ac7c-d97d5944549d.png)|![es_3](https://user-images.githubusercontent.com/1225438/148114558-30e5fe31-8e72-4461-9fe5-668dba12f283.png)|
|Pt|![pt_1](https://user-images.githubusercontent.com/1225438/148114561-2cf02 …
> Translate PIN code

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/network/network.dart
|English|Español|Português|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/148120142-e9685f48-8dbc-4d10-88e3-4acf95324031.png)|![es_1](https://user-images.githubusercontent.com/1225438/148120152-f26488ac-1cc4-4105-9ae7-b437edb0cf3d.png)|![pt_1](https://user-images.githubusercontent.com/1225438/148120160-3bf7b1e2-fc96-4b85-b396-a240e8e4178b.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/148120145-a2a32375-7f0e-4e9b-8dc1-9dac2f1d23d6.png)|![es_2](https://user-images.githubusercontent.com/1225438/148120154-7fe6e0a0-13c4-41d9-b8b7-baf981be7acd.png)|![pt_2](https://user-images.githubusercontent.com/1225438/148120163-de43d32c-224b-40ba-a8c1-a075837b1c4c.png)|
|![en_3](https://user-images.githubusercontent.com/1225438/148120147-333004b …
> Translate network page

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/add_funds/address_widget.dart
- lib/routes/add_funds/deposit_to_btc_address_page.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/148271795-0e400190-d1a4-4bbc-8c97-a9eefe0cd199.png)|![es](https://user-images.githubusercontent.com/1225438/148271803-f149b021-97b9-486a-ad2f-bdac0b556dec.png)|![pt](https://user-images.githubusercontent.com/1225438/148271804-ed2d710f-649d-4813-b17f-11e7f543e7ca.png)|
> Translate receive via BTC address page

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/create_invoice/create_invoice_page.dart
|Pt|Es|En|
|---|---|---|
|![pt](https://user-images.githubusercontent.com/1225438/148390258-d3928a49-7e1e-41de-a57a-3f83f5805886.png)|![es](https://user-images.githubusercontent.com/1225438/148390267-fbd3c30c-be26-4d12-9cf5-a9de5d0bd079.png)|![en](https://user-images.githubusercontent.com/1225438/148390271-7b9c063f-c799-4e87-b7f9-c7821e37adb9.png)|
> Translate invoice via lightning

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/connect_to_pay/payment_details_form.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/lnurl_fetch_invoice_page.dart
- lib/routes/spontaneous_payment/spontaneous_payment_page.dart
- lib/routes/withdraw_funds/withdraw_funds_page.dart
- lib/widgets/amount_form_field.dart
- lib/widgets/currency_converter_dialog.dart
- lib/widgets/escher_dialog.dart
- lib/widgets/payment_request_info_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/148402379-c2cc6fd2-956d-41a4-8252-84662acb28a5.png)|![es_1](https://user-images.githubusercontent.com/1225438/148402394-4d6caf1d-862e-4d9c-817a-c8129dba5a15.png)|![pt_1](https://user-images.githubusercontent.com/1225438/148402402-8ee18588-7cb6-4119-843d-eb03eaad47b1.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/148402386-5200bae5-9c7a-497c-9bf4-c92d724b577b.png)|![es_2](https://user-images.githubusercontent.com/1225438/148402399-035a559a-54e1-4dc3-8ec6-807ef3ce054c.png)|![pt_2](https://user-images.githubusercontent.com/1225438/148402404-a5dd099c-2691-4b56-9a5e-6acdff520fc3.png)|
|![en_3](https://user-images.githubusercontent.com/1225438/148402390-f3eed446-d5d5-40cb-8c32 …
> Translate amount form and currency converter dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/sync_progress_dialog.dart
- lib/routes/withdraw_funds/reverse_swap_confirmation.dart
- lib/routes/withdraw_funds/reverse_swap_page.dart
- lib/routes/withdraw_funds/swap_in_progress.dart
- lib/routes/withdraw_funds/withdraw_funds_page.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/148443211-9502bd89-5ffb-48b8-a6a8-b9b5072b8381.png)|![es_1](https://user-images.githubusercontent.com/1225438/148443217-45e451c0-7e27-4f9d-b71c-e0d8ff6b4d58.png)|![pt_1](https://user-images.githubusercontent.com/1225438/148443220-e09c7b58-e2ec-43e1-862d-985ac19f56d6.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/148443216-c3b3dbf0-2a10-4c85-8c77-3a2fe6f49028.png)|![es_2](https://user-images.githubusercontent.com/1225438/148443219-2e44efe9-2f0f-4dd7-95de-c5ac677fca76.png)|![pt_2](https://user-images.githubusercontent.com/1225438/148443222-37039d18-f2aa-44da-a81a-99471da25ea0.png)|
> Translate bitcoin withdraw

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/marketplace/marketplace.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/148446656-f965a6c0-3f96-45e2-8902-32f30b617553.png)|![es](https://user-images.githubusercontent.com/1225438/148446660-97209541-b13e-4352-bda1-8a45a5235ace.png)|![pt](https://user-images.githubusercontent.com/1225438/148446661-3ac5e6ae-b238-4c1d-a8d5-de44b6969d62.png)|
> Translate marketplace page (empty state)

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/account_required_actions.dart
- lib/routes/funds_over_limit_dialog.dart
- lib/routes/get_refund/get_refund_page.dart
- lib/routes/security_pin/remote_server_auth.dart
- lib/widgets/error_dialog.dart
- lib/widgets/send_onchain.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/148822108-f152e935-9ea7-4b96-aa27-c0ec5a2fa3af.png)|![es_1](https://user-images.githubusercontent.com/1225438/148822116-9a94a41d-52f3-4e34-a96c-84efc01f5c33.png)|![pt_1](https://user-images.githubusercontent.com/1225438/148822120-4188b717-2318-4129-a2ed-51852d7bd244.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/148822113-f259eca3-8cf7-4993-bb3e-c499360ca11b.png)|![es_2](https://user-images.githubusercontent.com/1225438/148822117-a54d4821-aed7-415d-8c0f-6b7fcef373e5.png)|![pt_2](https://user-images.githubusercontent.com/1225438/148822122-886a7510-b7fe-47fa-94bb-20cf0a2f1cb8.png)|
> Translate remote server, refund and error dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/lnurl_success_action_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/149000951-dbb92435-a5dd-4a25-8b6d-cf033a9b7855.png)|![es](https://user-images.githubusercontent.com/1225438/149000962-060675b5-aa18-420d-90ba-f28c0ce333da.png)|![pt](https://user-images.githubusercontent.com/1225438/149000968-ca1e0ff0-5ec6-46cc-a87a-add1976241c3.png)|
> Translate ln url success dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/avatar_picker.dart
It seems the avatar picker is not being used.
Translating it in case of adding this page back.
> Translate avatar picker

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/beta_warning_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/149193986-93395780-1bfa-49e6-bd89-0db398afcefd.png)|![es_1](https://user-images.githubusercontent.com/1225438/149193998-3f5c9d0f-a8f9-4899-8454-1f938590d5b0.png)|![pt_1](https://user-images.githubusercontent.com/1225438/149194003-c76b0656-912c-433b-a915-790a8d894098.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/149193993-92536417-b183-4e4d-98bf-309550913996.png)|![es_2](https://user-images.githubusercontent.com/1225438/149194001-3129cb32-6263-4ed9-a019-23a474f04147.png)|![pt_2](https://user-images.githubusercontent.com/1225438/149194004-3970afb1-0311-4295-ab23-faa72b315506.png)|
> Translate beta warning message

- lib/l10n/app_fi.arb
- lib/l10n/fi_messages.dart
- lib/l10n/finnish_implements_duration_locale.dart
Review @ademar111190 and comment, please?
> Add finnish translations to "duration" and app_fi.arp + typo fix

- pubspec.yaml
Related: https://github.com/breez/anytime_podcast_player/pull/39
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/150352859-32ebaa8e-f3da-4721-93ae-4f41fd1e9751.jpeg)|![after](https://user-images.githubusercontent.com/1225438/150353079-d15a0e92-b98c-4ca9-98a0-4658241df708.png)|
> Update anytime to fix NPE

- lib/utils/lnurl.dart
LUD-17: link https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md
The code running on the app.
Related PR: https://github.com/breez/breez/pull/147
https://user-images.githubusercontent.com/1225438/150155040-5eb3692d-c3f4-4ffc-aa49-b03527216bbf.mp4
https://user-images.githubusercontent.com/1225438/150155054-e2f118ba-dd78-4f2b-91bb-6824f9f14096.mp4
https://user-images.githubusercontent.com/1225438/150155068-59849352-ddde-43da-a39f-c0e2ffa90d1c.mp4
> Add support to LUD-17 scheme

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/payment_request_info_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/150538962-c7a3617b-4679-4129-845f-fd895231c6e2.png)|![es](https://user-images.githubusercontent.com/1225438/150538970-9041d6b7-b242-47df-91cf-d0121030a191.png)|![pt](https://user-images.githubusercontent.com/1225438/150538973-417f84f0-3356-4729-afbf-40869d661e49.png)|
> Translate payment request info dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/lsp_fee.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/150586676-a2b9f636-0722-4ff0-a9c3-c04031af7031.png)|![es](https://user-images.githubusercontent.com/1225438/150586679-a26bb857-68e8-4f4d-a240-9eacc1bd9119.png)|![pt](https://user-images.githubusercontent.com/1225438/150586680-aa5ede87-000f-4a44-90d4-8cff25aee071.png)|
> Translate lsp fee dialog

- lib/home_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/lost_card_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/150835878-daf1341f-0c60-4a32-ac64-bc9cfa9e96f9.png)|![es_1](https://user-images.githubusercontent.com/1225438/150835890-d104f983-f47b-4eed-a75c-10ba7d22542a.png)|![pt_1](https://user-images.githubusercontent.com/1225438/150835895-73c904d6-7f19-402f-a8c1-2bb321934cf1.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/150835886-935d7045-a9db-4c2d-b324-9dd6eda56836.png)|![es_2](https://user-images.githubusercontent.com/1225438/150835891-c5179653-4ea5-42a7-beb5-cc34e75ca014.png)|![pt_2](https://user-images.githubusercontent.com/1225438/150835898-79238749-4a21-4a1f-b574-c6662bacaf4e.png)|
> Translate lost card dialog

- android/app/build.gradle
- android/build.gradle
- play-services-auth: `19.2.0` => `20.0.1`
- commons-io: `2.4` => `2.6`
- appcompat: `1.3.1` => `1.4.1`
- lifecycle-process: `2.3.0` => `2.4.0`
- material: `1.4.0` => `1.5.0`
- build tools: `7.0.3` => `7.0.4`
> Update Android native libs

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/close_popup.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/150969350-be28b93c-0cba-4c78-b7b0-f846ad27cc5e.png)|![es](https://user-images.githubusercontent.com/1225438/150969356-60106873-7439-468a-87ce-06b42ae8898b.png)|![pt](https://user-images.githubusercontent.com/1225438/150969358-d74a1dfe-c76d-46bb-addc-832acb8d751a.png)|
> Translate close popup

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/breez_avatar_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/150981111-896a7d9a-0cee-40bd-b793-c0605df871f8.png)|![es](https://user-images.githubusercontent.com/1225438/150981114-ef62845e-f220-40a5-b5e1-7b77a17bea47.png)|![pt](https://user-images.githubusercontent.com/1225438/150981117-83c8f9ae-f8dc-4109-b5c8-e2f3c73ec099.png)|
> Translate avatar dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/widgets/barcode_scanner_placeholder.dart
It seems this widget is not used anymore.
> Translate scanner placeholder

- lib/routes/fiat_currencies/fiat_currency_settings.dart
Fixes https://github.com/breez/breezmobile/issues/715
How it looks now:
https://user-images.githubusercontent.com/1225438/151382137-ab7ac80a-394b-4506-bd3e-b92514dd6bac.mp4
> Fix fiat currencies reorder

- lib/widgets/practicles_animations.dart
- pubspec.yaml
[Simple animations](https://pub.dev/packages/simple_animations) has breaking changes, so this PR updates it
How the particle animation looks like with the changes:
https://user-images.githubusercontent.com/1225438/151601796-6d14af56-5c6c-4f1d-acbd-f741d7c6e64a.mp4
> Update simple animations

- lib/l10n/app_pt.arb
> Minor changes PT-BR

- lib/l10n/app_es.arb
> Fixed typo

- lib/routes/charge/pos_invoice_items_view.dart
How it looks like now:
https://user-images.githubusercontent.com/1225438/153225719-426ea309-9ed0-407b-8f81-25781e43c37c.mp4
> Changes menu behaviour

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/charge/pos_payment_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/153616843-87464fd5-ff70-48e9-b7ec-6982181107e9.png)|![es](https://user-images.githubusercontent.com/1225438/153616839-f23f3a1a-4155-46da-9cf1-12599089f675.png)|![pt](https://user-images.githubusercontent.com/1225438/153616831-de0fd561-0201-4be6-a7b2-9612ff6c0747.png)|
> Translate pos payment dialog

- lib/logger.dart
Sometimes the logger crashes because of this NPE, this PR fixes it.
> Fix NPE on logger

- lib/handlers/check_channel_connection_handler.dart
- lib/home_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
Fixes https://github.com/breez/breezmobile/issues/107
https://user-images.githubusercontent.com/1225438/152033822-bf9c7436-bb38-451c-9c47-6218df19b729.mp4
> Add channel connection check

- lib/widgets/single_button_bottom_bar.dart
Thanks @bitcoinuser for the bug report.
> Fix single button bar text gone bug

- lib/bloc/podcast_payments/actions.dart
- lib/bloc/podcast_payments/podcast_payments_bloc.dart
- lib/routes/podcast/boost_message_dialog.dart
- lib/routes/podcast/payment_adjustment.dart
Reference: https://github.com/lightning/blips/blob/master/blip-0010.md
> Add sender name to boostagram and increase message size to 128 characters

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/charge/items/catalog_item.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/159069931-f4a463b3-9134-499a-8262-20cdcf3a8f0c.png)|![es](https://user-images.githubusercontent.com/1225438/159069938-f2e2ca04-7fdf-4a87-bad0-a05172c8433a.png)|![pt](https://user-images.githubusercontent.com/1225438/159069940-04b3b070-b006-4f44-abf5-2fd0bc7a974d.png)|
> Translate catalog item

- lib/bloc/pos_catalog/sqlite/db.dart
- lib/routes/dev/dev.dart
A developer function to help the development.
> Add import export product db to developer tools

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/create_invoice/qr_code_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/159994969-77785504-3ad0-4772-9580-d2cd14cfede6.png)|![es](https://user-images.githubusercontent.com/1225438/159994977-36c60914-dd71-4ad3-b0de-ff85ffae6e9d.png)|![pt](https://user-images.githubusercontent.com/1225438/159994979-a214f3eb-ffd9-4fc3-a961-38c0e968b375.png)|
> Translate QR code dialog

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/podcast/add_funds_message.dart
- lib/routes/podcast/anytime_downloader.dart
- lib/routes/podcast/boost.dart
- lib/routes/podcast/boost_message_dialog.dart
- lib/routes/podcast/confetti.dart
- lib/routes/podcast/custom_amount_dialog.dart
- lib/routes/podcast/custom_amount_form.dart
- lib/routes/podcast/episode_metadata_loader.dart
- lib/routes/podcast/payment_adjuster.dart
- lib/routes/podcast/payment_adjustment.dart
- lib/routes/podcast/podcast_index_api.dart
- lib/routes/podcast/share_episode_button.dart
- lib/routes/podcast/share_podcast_button.dart
- lib/routes/podcast/speed_selector.dart
- lib/widgets/payment_details_dialog.dart
|En|Es|Pt|
|---|---|---|
|![en_1](https://user-images.githubusercontent.com/1225438/160648896-38dfc0ec-468f-4e24-8d39-6aeaa81b9790.png)|![es_1](https://user-images.githubusercontent.com/1225438/160648906-f8e7c4ad-d677-4c78-be5d-af474577e583.png)|![pt_1](https://user-images.githubusercontent.com/1225438/160648910-6b8e99e4-4ed1-47be-8a60-f54c551fee27.png)|
|![en_2](https://user-images.githubusercontent.com/1225438/160648905-12b70ed5-d346-4888-989e-47c4aa7a2c1a.png)|![es_2](https://user-images.githubusercontent.com/1225438/160648908-b7f371b2-ac82-4b8d-bbc0-744da4fc6fac.png)|![pt_2](https://user-images.githubusercontent.com/1225438/160648911-d2ae2efd-24b2-437d-b920-236a1cab746d.png)|
> Translate custom podcast components

- lib/bloc/pos_catalog/model.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
As we talked on Telegram @kingonly @tlindi
> Translate custom pos item name

- lib/bloc/account/account_bloc.dart
- lib/bloc/account/account_model.dart
- lib/bloc/pos_catalog/model.dart
- lib/bloc/pos_catalog/repository.dart
- lib/bloc/pos_catalog/sqlite/repository.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_pt.arb
- lib/routes/transactions/pos_payment_item.dart
- lib/routes/transactions/pos_payments_list.dart
- lib/routes/transactions/pos_transactions_page.dart
https://user-images.githubusercontent.com/1225438/160919998-c127dac2-cc63-4fb9-8725-b084606d16da.mp4
> Add fiat value to payment item

- lib/bloc/account/fiat_conversion.dart
- lib/services/currency_data.dart
- lib/widgets/currency_amount_field_formatter.dart
- lib/widgets/currency_converter_dialog.dart
Fixes https://github.com/breez/breezmobile/issues/760
https://user-images.githubusercontent.com/1225438/163410546-289ec84a-b22f-4fd0-a523-79f7026e7dc8.mp4
> Add right sign currency support in currency converter

- lib/routes/podcast/speed_selector.dart
Merging the changes from https://github.com/breez/breezmobile/pull/889 into the maste
> Playback Speed Range increased to 3* (#889)

- lib/bloc/account/account_model.dart
- lib/routes/home/payment_item_avatar.dart
- lib/routes/lnurl_fetch_invoice_page.dart
- lib/services/breezlib/data/rpc.pb.dart
- lib/services/breezlib/data/rpc.pbenum.dart
- lib/services/breezlib/data/rpc.pbgrpc.dart
- lib/services/breezlib/data/rpc.pbjson.dart
- lib/utils/lnurl_metadata_extension.dart
|To pay|Payed|
|---|---|
|![Screenshot_20220420-162357_Breez_Debug](https://user-images.githubusercontent.com/1225438/164747773-d8782589-a665-4fe7-9042-e7f7fc174898.png)|![Screenshot_20220422-122629_Breez_Debug](https://user-images.githubusercontent.com/1225438/164747784-ead05f13-92df-41ec-9bc6-518251c6fa4e.png)|
Related: https://github.com/breez/breez/pull/154
> Add support to LN-URL image metadata

- lib/l10n/app_fr.arb
I did my best to translate the whole application into French!
I know many people in France for whom this is important, I hope to have it on the stores soon :)
> Translation of the app into French

- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/home_page.dart
- lib/l10n/locales.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- lib/utils/locale.dart
Integrate French translation from this pr https://github.com/breez/breezmobile/pull/904
Thank you @trigger67 🙏 
||||
|---|---|---|
|![Screenshot_20220505-143026_Breez_Debug](https://user-images.githubusercontent.com/1225438/166983019-752d7733-3439-42f7-a470-702b7e4dee5b.png)|![Screenshot_20220505-143032_Breez_Debug](https://user-images.githubusercontent.com/1225438/166983029-95b2ca54-9745-411b-b43c-192886847718.png)|![Screenshot_20220505-143037_Breez_Debug](https://user-images.githubusercontent.com/1225438/166983032-8e4d574d-eb2f-460e-b82b-c7787d72b0e3.png)|
|![Screenshot_20220505-143105_Breez_Debug](https://user-images.githubusercontent.com/1225438/166983034-8590c81d-ea59-439a-8329-c98930a63be0.png)|![Screenshot_20220505-143117_Breez_Debug](https://user-images.githubuse …
> Add french translation

- lib/bloc/app_blocs.dart
- lib/bloc/pos_catalog/bloc.dart
- lib/bloc/user_profile/breez_user_model.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_fr.arb
- lib/l10n/app_pt.arb
- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/sale_view.dart
- lib/routes/settings/pos_settings_page.dart
Fixes https://github.com/breez/breezmobile/issues/903
|Default|Custom|Cart|
|---|---|---|
|![Screenshot_20220506-115458_Breez_Debug](https://user-images.githubusercontent.com/1225438/167160958-09cc037b-d027-46b4-8e25-eb655f921be5.png)|![Screenshot_20220506-115443_Breez_Debug](https://user-images.githubusercontent.com/1225438/167160957-d2c1a55a-830b-4330-8232-11a346ff1dd5.png)|![Screenshot_20220506-115429_Breez_Debug](https://user-images.githubusercontent.com/1225438/167160951-0c6d1740-9968-4179-b8e1-4828d3102f0c.png)|
> Add default note to POS

- README.md
After trying to build and run Breez application for a while, I would like to reorganize and update README file so that it provide more detailed (a little bit) and updated information for the new contributors.
> readme: reorganize setting up part in README.md

- pubspec.lock
- pubspec.yaml
A minor dependency regression did happen with the last merges, this commit fixes it
> Fix minor dependency regression

- lib/bloc/pos_catalog/model.dart
- lib/routes/transactions/pos_payment_item.dart
It is not necessary to show bitcoin or satoshi values on the list
> Hide satoshi detail on transactions page

- lib/bloc/app_blocs.dart
- lib/bloc/backup/backup_bloc.dart
- lib/bloc/payment_options/payment_options_bloc.dart
- lib/bloc/user_profile/backup_user_preferences.dart
- lib/bloc/user_profile/breez_user_model.dart
- lib/routes/payment_options/payment_options_page.dart
- Add theme, lightning fees options to backup app data.
- Remove temporary setttings such as current currency, fiatCurrency, posCurrencyShortName from backup app data.
- Default to first item on preferredCurrencyList if preferredCurrencyList does not contain default fiatCurrency on restore.
> Changes to backup app data

- lib/bloc/podcast_history/sqflite/podcast_history_database.dart
- lib/routes/dev/dev.dart
> Added functionality to reset podcast history local db

- lib/bloc/podcast_payments/podcast_payments_bloc.dart
> Fix podcast history not recording due to async calls

- lib/l10n/app_fr.arb
> Add missing french translation

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/l10n/locales.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- lib/utils/locale.dart
Thank you @theDavidCoen for the Italian translation https://github.com/breez/breezmobile/pull/951
> Add scaffold to Italian language

- lib/bloc/lnurl/lnurl_bloc.dart
Context:
https://github.com/breez/breezmobile/issues/949
https://github.com/fiatjaf/go-lnurl/issues/9
The fixes of go lnurl are not applied yet
> Fix lnurl case

- lib/l10n/locales.dart
- lib/user_app.dart
- lib/widgets/barcode_scanner_placeholder.dart
- pubspec.lock
- pubspec.yaml
Issue: https://github.com/breez/breezmobile/issues/955
- Enable Italian thank you @theDavidCoen
- Add Spanish
- Update Portuguese
- Make room for French and Finnish translations
- Move generated files to the generated folder
- Update L to take advantage of generated code
Related https://github.com/breez/anytime_podcast_player/commit/06c1af145c8e646f8ec0935c33d1cf6051210004
> Sync Anytime to pull its news translations improvements and additions

- lib/bloc/podcast_clip/podcast_clip_bloc.dart
- lib/routes/podcast/podcast_clip.dart
Minor improvements in the clip's functionality
<p float="middle">
</p>
> Clips: Fixed clip cancellation

- lib/bloc/podcast_clip/podcast_clip_bloc.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_fr.arb
- lib/l10n/app_it.arb
- lib/l10n/app_pt.arb
- lib/routes/podcast/podcast_clip.dart
How does it look like
https://user-images.githubusercontent.com/1225438/185950369-ac165302-bb40-465d-a61d-974290c24b40.mp4
https://user-images.githubusercontent.com/1225438/185950392-9f534e00-c5a1-41ed-af7d-462264e58a40.mp4
> Fix clip functionality plus some improvements

- lib/bloc/csv_exporter.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_fr.arb
- lib/l10n/app_it.arb
- lib/l10n/app_pt.arb
- test/bloc/csv_exporter_test.dart
Fixes https://github.com/breez/breezmobile/issues/981
I did add a few tests to the CSV exporter as well.
> Add fee to cvs exporter

- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/l10n/app_sv.arb
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- lib/utils/locale.dart
Thank you Roberth for your work on Swedish translation 🙏
> Add Swedish support 🇸🇪 🇦🇽 🇪🇺 🚀 

- pubspec.lock
- pubspec.yaml
> Update anytime lib

- lib/routes/charge/pos_invoice.dart
- lib/routes/charge/pos_invoice_items_view.dart
|Ligth|Dark|
|---|---|
|![keypad ligth](https://user-images.githubusercontent.com/1225438/203329019-22d757e4-232b-4b94-8017-45a44f10814f.png)|![keypad dark](https://user-images.githubusercontent.com/1225438/203329011-bd34146b-8647-4177-9d66-50d48ecf6d43.png)|
|![items dark](https://user-images.githubusercontent.com/1225438/203329017-ff764970-55e8-4b39-8958-f4de2e413e4d.png)|![items ligth](https://user-images.githubusercontent.com/1225438/203329020-e78398f2-8b81-4766-b98a-d56d41e22514.png)|
> Move PoS button to the bottom

- lib/widgets/designsystem/button/action_button.dart
- lib/widgets/designsystem/variant.dart
- lib/widgets/preview/preview.dart
|Ligth|Dark|
|---|---|
|![ligth](https://user-images.githubusercontent.com/1225438/202759414-024f47ea-8c32-4e3c-8caa-7c6ca09a7c0e.png)|![dark](https://user-images.githubusercontent.com/1225438/202759427-c183ed35-e3cc-4659-8264-df20556adf92.png)|
> Add action button

- lib/widgets/designsystem/button/action_button.dart
- lib/widgets/designsystem/variant.dart
- lib/widgets/single_button_bottom_bar.dart
|Screen|Light|Dark|
|---|---|---|
|send payment|![send payment l](https://user-images.githubusercontent.com/1225438/205917997-1134a134-eb68-4ed5-81fe-381a83f88250.png)|![send payment d](https://user-images.githubusercontent.com/1225438/205918002-4e18605b-3d8c-4e4d-962d-0ac3fd741e24.png)|
|receive via btc address|![receive via btc address l](https://user-images.githubusercontent.com/1225438/205918005-6d36487f-64e4-46f7-aa56-03eee747a333.png)|![receive via btc address d](https://user-images.githubusercontent.com/1225438/205918003-ca141791-b584-46b5-b092-197dc44ec2ea.png)|
|add item|![add item l](https://user-images.githubusercontent.com/1225438/205918017-bc24709e-83c5-4214-8b91-210f7e312619.png)|![add item d](https://user-images.githubusercontent.com/1225438/205918008-138c …
> Change single button bar to action button

- .gitignore
- l10n.yaml
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/l10n/app_de.arb
- lib/l10n/app_it.arb
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- lib/utils/locale.dart
- test/l10n/localized_text_test.dart
Thank you @caloon and @arbadacarbaYK for the translations, feel free to make any changes to improve the translations 🙏
> Add German translation 🇩🇪🇦🇹🇨🇭🇱🇺🇱🇮🇧🇪

- lib/routes/network/network.dart
> Apply some changes on network page UI

- lib/routes/home/qr_action_button.dart
These logs can help the investigation of some bugs with the QR code reader as the entry point.
> Add some log entries to QR action button

- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_fi.arb
- lib/l10n/app_fr.arb
- lib/l10n/app_it.arb
- lib/l10n/app_pt.arb
- lib/l10n/app_sv.arb
- lib/lnurl_success_action_dialog.dart
- lib/logger.dart
- lib/routes/add_funds/address_widget.dart
- lib/routes/charge/pos_payment_dialog.dart
- lib/routes/create_invoice/qr_code_dialog.dart
- lib/routes/dev/dev.dart
- lib/routes/get_refund/wait_broadcast_dialog.dart
- lib/routes/home/payments_filter.dart
- lib/routes/podcast/share_episode_button.dart
- lib/routes/podcast/share_podcast_button.dart
- lib/routes/settings/pos_settings_page.dart
- lib/routes/transactions/pos_transactions_page.dart
- lib/routes/unexpected_error_dialog.dart
- lib/services/device.dart
- lib/widgets/collapsible_list_item.dart
- lib/widgets/no_connection_dialog.dart
- lib/widgets/payment_details_dialog.dart
- lib/widgets/restore_dialog.dart
- pubspec.lock
- pubspec.yaml
- We are already using share plus that does the same
- Share extended is not updated for years
- Share plus supports mac/linux/windows and share extended not.
> Remove share extended

- lib/l10n/app_fi.arb
- lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart
Fixes https://github.com/breez/breezmobile/issues/1034
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/210806368-ddb20c98-1895-4da9-8dd7-be9b70cfedfb.png)|![after](https://user-images.githubusercontent.com/1225438/210806364-1c35d78c-4632-43a2-9837-cfd4ac311d72.png)|
> Fix backup message heigth

- lib/routes/network/network.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/widgets/designsystem/switch/simple_switch.dart
|Small font|Normal font|Big font|
|---|---|---|
|![seb small](https://user-images.githubusercontent.com/1225438/214041561-9978f947-7931-4199-94f3-fd7631f3fc2b.png)|![seb normal](https://user-images.githubusercontent.com/1225438/214041562-8395341f-97c5-4b55-a853-27297cf73889.png)|![seb big](https://user-images.githubusercontent.com/1225438/214041551-202f4908-6108-4b84-9290-ece3712737a7.png)|
|![network small](https://user-images.githubusercontent.com/1225438/214041563-0ce90ef5-35ea-4765-9dc6-1eeb35218802.png)|![network normal](https://user-images.githubusercontent.com/1225438/214041569-61a45424-51e7-4ca4-916e-aea63ae1937d.png)|![network big](https://user-images.githubusercontent.com/1225438/214041568-9353f5b3-3c7c-41fa-afd5-70f6002675b5.png)|
> Create Simple Switch to have an unique behavior across pages

- lib/bloc/account/account_bloc.dart
Referes to https://github.com/breez/breez/pull/176
Remove calls to _.setBackupTorConfig(torConfig);_ since it is removed from bridge
> tor-hotfix

- ios/Podfile.lock
- lib/bloc/lnurl/lnurl_model.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/lnurl_fetch_invoice_page.dart
- pubspec.lock
- test/bloc/csv_exporter_test.dart
This pr refers to #1057 where the amount of lnurlwithdraw where filled by default. 
- remove the autofilling
- add  _isFixedAmount_  to class  _PayFetchResponse_ and _WithdrawFetchResponse_
- display invoice limit if min and max withdraw are not the equal
Test where done with https://lnurl.fiatjaf.com/
> remove autofil lnurl-withdraw

- lib/routes/podcast/boost.dart
- lib/routes/podcast/payment_adjuster.dart
- lib/routes/podcast/widget/number_panel.dart
|Before|After|
|---|---|
|![error](https://user-images.githubusercontent.com/1225438/219060690-7bd78697-a525-4b46-8025-1f5a8d7ad0d9.png)|![fixed](https://user-images.githubusercontent.com/1225438/219060684-979793dc-d632-433c-acf8-4f2fdf51b929.png)|
> Fix autosize text and extract number panel

- lib/routes/fiat_currencies/fiat_currency_settings.dart
> Fix fiat currencies first load

- README.md
- ios/Runner.xcodeproj/project.pbxproj
- Corrected the name of the bindings framework built from the breez project
- Corrected the path where GoogleServices-info.plist should be copied to
- Markdown cleanup
> Improvements to iOS

- conf/simnet/breez.conf
- conf/simnet/lnd.conf
- lib/routes/create_invoice/qr_code_dialog.dart
I encountered a bunch of issues when trying to run my own debug application with my own simnet. The modifications to the config files fix the simnet connection and the error handling in the QR code warning message fixes a nullptr crash when running on a simnet.
> Fix the broken simnet configuration

- lib/routes/home/payment_item_avatar.dart
This PR addresses 
- https://github.com/breez/breezmobile/issues/1084
Fixed avatar icon of deposit transactions.
> Show '+' icon for deposit transactions

- lib/bloc/account/account_model.dart
- pubspec.yaml
This pr references issue  https://github.com/breez/breezmobile/issues/1087.
- Removed displaying the _maxPaymentAmount_
- Removed unused function _validateOutgoingOnChainPayment_
> Limit message correction

- android/app/build.gradle
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java
- lib/bloc/backup/backup_bloc.dart
- lib/bloc/backup/backup_model.dart
- lib/routes/security_pin/backup_phrase/verify_backup_phrase_page.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/widgets/enable_backup_dialog.dart
My approach here is to trigger the sign again, which I believe is reasonable as we can know the failure is a [UserRecoverableAuthException](https://developers.google.com/android/reference/com/google/android/gms/auth/UserRecoverableAuthException)
Fixes https://github.com/breez/breezmobile/issues/1076
How it looks like: (the black screen is not visible IRL just on the video record, probably some protection made by google sign in SDK)
https://user-images.githubusercontent.com/1225438/224729722-660f4960-b0ec-409c-89e5-146dadfe393d.mp4
> Fix multiple account backup

- lib/routes/get_refund/wait_broadcast_dialog.dart
- lib/utils/exceptions.dart
- pubspec.lock
- pubspec.yaml
- test/utils/exceptions_test.dart
Fixes https://github.com/breez/breezmobile/issues/1095
> Extract and replace fee too high error message

- lib/routes/get_refund/get_refund_page.dart
- lib/routes/get_refund/widget/get_refund_action.dart
- lib/routes/get_refund/widget/get_refund_list.dart
- lib/routes/get_refund/widget/get_refund_title.dart
|Normal font|Big font|Normal font big text|
|---|---|---|
|![normal-font](https://user-images.githubusercontent.com/1225438/227271085-cc8a8b47-a1a2-48e6-9153-5ac94df62baf.png)|![big-font](https://user-images.githubusercontent.com/1225438/227271068-e37f30bb-3713-4d63-bb78-8eed837f4656.png)|![normal-font-big-word](https://user-images.githubusercontent.com/1225438/227271080-694badd8-f6d9-4568-b6d1-3fa7a8a95834.png)|
> Fix broadcasted button on large font plus widget extraction

- android/app/build.gradle
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java
https://user-images.githubusercontent.com/1225438/227606638-e936cfd8-7739-4d54-9d28-fba46d8cdb11.mp4
> Add a recover flow when user has removed the permission of its account

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- pubspec.lock
- pubspec.yaml
- test/utils/exceptions_test.dart
Thank you @CS-HODL for adding the translation 🙏
> Add sk translation 🇸🇰🇪🇺🇷🇸

- lib/home_page.dart
- lib/routes/home/bottom_actions_bar.dart
- lib/routes/home/qr_action_button.dart
- lib/utils/stream_builder_extensions.dart
- lib/widgets/home/home_app_bar.dart
- lib/widgets/home/home_navigation_drawer.dart
- pubspec.lock
- pubspec.yaml
This fixes some crashes on layout build time present at home and at the podcast page, the podcast fixes are in detail here https://github.com/breez/anytime_podcast_player/pull/46
> Fix layout crashes

- lib/routes/charge/pos_invoice_items_view.dart
This fixes #1130. 
Tested of android and iOS
https://user-images.githubusercontent.com/36157890/234887150-1baa54a9-d968-4ec1-8146-35b26ae8bfe4.mov
> fix #1130 sorting

- lib/routes/podcast/speed_selector.dart
- lib/services/download_manager.dart
- pubspec.lock
- pubspec.yaml
This is a fix for issue #1145 where the buttons had wrong colour.
> fix background on speed button #1145

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- pubspec.lock
- pubspec.yaml
- test/utils/exceptions_test.dart
Thank you very much @n1kcha for the translations 🙏
> Add Greek support 🇬🇷🇨🇾🇪🇺🤔🏛️🏺💪💪💪

- lib/utils/node_id.dart
- lib/widgets/enter_payment_info_dialog.dart
We did not check if the value of the payemnt is a lnurl for the `EnterPaymentInfoDialog`.
fixes #1164
> check `isLNURL` in `EnterPaymentInfoDialog`

- lib/bloc/podcast_payments/podcast_payments_bloc.dart
Fixes #1123
The guid should be sent on the episode_guid field and the episode id on the itemID field
> fix send guid on episode_guid and id on itemID boostagram field

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
Fixes 
- #1184
Update dependencies to latest
> Fix regression - Podcast player dropdown menu icon

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/security_pin/security_pin_page.dart
- lib/utils/date.dart
- pubspec.lock
- pubspec.yaml
- test/utils/exceptions_test.dart
Thank you @CS-HODL for the translations 🙏
> Add Czech language support 🇨🇿🇪🇺

- lib/routes/initial_walkthrough/initial_walkthrough.dart
- lib/routes/security_pin/remote_server_auth/remote_server_auth.dart
- lib/widgets/enable_backup_dialog.dart
Tested with remote storage.
@erdemyerebasmaz Do you think this cause unwanted side effects with iCloud or GDrive ?
> Ubbabeck security page refactor

- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java
- lib/bloc/backup/backup_bloc.dart
- lib/bloc/backup/backup_model.dart
- pubspec.lock
- pubspec.yaml
<video src="https://github.com/breez/breezmobile/assets/1225438/1990a555-c403-4004-ac8f-7c79cb890354" />
> Add google sign in not available error

- lib/handlers/lnurl_handler.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/utils/exceptions.dart
fixes #1176 
If the returned string indicates that there is no internet connection, we'll display the following error both for lnurl and create invoice.
https://github.com/breez/breezmobile/assets/36157890/9607e918-6bab-4b6c-bd0c-7d76f363a5ac
> update error handling when not connected to lsp

- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java
- android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java
- ios/Plugins/Breez/BreezLib/Breez.swift
- ios/Plugins/Breez/BreezLib/GoogleAuthenticator.swift
- ios/Plugins/Breez/BreezLib/iCloudBackupProvider.swift
- ios/Runner/Info.plist
- lib/bloc/backup/backup_actions.dart
- lib/bloc/backup/backup_bloc.dart
- lib/bloc/backup/backup_model.dart
- lib/routes/account_required_actions.dart
- lib/routes/backup_in_progress_dialog.dart
- lib/routes/initial_walkthrough/dialogs/restore_dialog.dart
- lib/routes/initial_walkthrough/dialogs/select_backup_provider_dialog.dart
- lib/routes/initial_walkthrough/initial_walkthrough.dart
- lib/routes/security_pin/backup_phrase/verify_backup_phrase_page.dart
- lib/routes/security_pin/remote_server_auth/remote_server_auth.dart
- lib/routes/security_pin/security_and_backup/backup_tiles/backup_provider_tile.dart
- lib/routes/security_pin/security_and_backup/backup_tiles/remote_server_credentials_tile.dart
- lib/routes/security_pin/security_and_backup/security_and_backup_page.dart
- lib/services/breezlib/breez_bridge.dart
- lib/widgets/enable_backup_dialog.dart
- lib/widgets/error_dialog.dart
- pubspec.lock
- pubspec.yaml
- test/bloc/backup/backup_bloc_test.dart
This PR contains no functional changes.
It includes refactoring changes to make it easier to work on Security & Backup page for devs.
- SecurityPage is renamed to Security & Backup page.
-  All helper methods to build widgets are converted to Widgets.
- Tile widgets are grouped by their type, Security or Backup. 
- Their shared functions are on Security & Backup page to increase reusability.
- Although, this may not be that great in terms of readability.
> Refactor Security & Backup page

- android/app/build.gradle
- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/home_page.dart
- lib/routes/charge/items/catalog_item.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/create_invoice/create_invoice_page.dart
- lib/routes/home/bottom_actions_bar.dart
- lib/routes/marketplace/marketplace.dart
- lib/theme_data.dart
- lib/user_app.dart
- lib/widgets/home/home_app_bar.dart
- lib/widgets/home/home_navigation_drawer.dart
- pubspec.lock
This PR addresses regressions surrounding SystemUiOverlayStyle, mainly on Android as there has been behavioral changes for API level 29+, and also introduces additional visual improvements.
- Try to match system navigation bar's color with the topmost(as in z-index) background color that's adjacent to system navigation bar, _with the help of AnnotatedRegion_
- OS specific status bar improvements
- Pass Item info as route arguments to ItemPage
- Remove unused imports
- Barrier scrim does not apply to system navigation bar color on Android
> Improvements to SystemUiOverlayStyle(system status & navigation bar)

- lib/home_page.dart
- lib/routes/charge/pos_invoice_items_view.dart
- lib/routes/dev/dev.dart
- lib/routes/home/bottom_actions_bar.dart
- lib/routes/marketplace/lnurl_webview.dart
- lib/routes/marketplace/marketplace.dart
- lib/routes/podcast/podcast_clip/podcast_clip_detail_bottom_sheet.dart
- lib/routes/podcast/speed_selector.dart
- lib/routes/podcast/transport_controls.dart
- lib/routes/unexpected_error_dialog.dart
- lib/widgets/home/home_app_bar.dart
- lib/widgets/home/home_navigation_drawer.dart
- lib/widgets/processing_payment_dialog.dart
- lib/widgets/sync_loader.dart
- Refactor occurrences of 
- Theme.of(context) as themeData.
- L.of(context) as localizations.
- Replace BreezTranslations.of(context) with context.texts()
> Refactor occurrences of BuildContext extensions

- lib/routes/home/bottom_actions_bar.dart
Fixes https://github.com/breez/breezmobile/issues/1223
Add an error dialog if pushing the receive via BTC page fails
https://github.com/breez/breezmobile/assets/1225438/81eb1969-b277-43e7-afd3-8d9fc361fdea
> Add error dialog when receive via BTC fails

- android/app/build.gradle
- ios/Runner/Info.plist
- lib/routes/account_required_actions.dart
- lib/routes/funds_over_limit_dialog.dart
fixes #1228 
test: awaiting failed swap transaction to be confirmed on chain...
> build if snapshot has data

- android/build.gradle
- ios/Podfile.lock
- lib/routes/home/qr_action_button.dart
- lib/routes/qr_scan.dart
- pubspec.lock
- pubspec.yaml
Fix https://github.com/breez/breezmobile/issues/1231
I took the opportunity to update the mobile scan lib (I had to update the kotlin too) and add logs with a more specific tag
The problem was `detectionSpeed: DetectionSpeed.noDuplicates,` being kept between sessions, so I just removed it as we are controlling on our side to consume just one code anyway.
- Open any flow that use the camera qr code reader
- Read a qr code
- close the triggered flow and open the camera again
- Read the same qr code previously read
- The flow should be triggered again
> Fix same invoice not read by qrcode scan twice in a row

- ios/Runner/Info.plist
- lib/bloc/user_profile/default_profile_generator.dart
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/security_pin/security_and_backup/security_tiles/pin_interval_tile.dart
- lib/utils/date.dart
- pubspec.lock
- pubspec.yaml
- test/utils/exceptions_test.dart
Thank you @ch0k1 and @Nackoo2000 for the translations
|||||
|![home](https://github.com/breez/breezmobile/assets/1225438/4c695133-9a91-466a-8da0-3ee1150cde36)|![drawer](https://github.com/breez/breezmobile/assets/1225438/0161a472-0e47-4f9c-a84e-263f52e782aa)|![menu2](https://github.com/breez/breezmobile/assets/1225438/164e5b91-1ccb-4028-be57-83ecbb727857)|![menu1](https://github.com/breez/breezmobile/assets/1225438/ffac0b78-95ac-4973-92b3-4a9b5041f1eb)|
|![quit](https://github.com/breez/breezmobile/assets/1225438/bf25dcf2-56cb-43fa-be12-9971413eb01f)|![pos3](https://github.com/breez/breezmobile/assets/1225438/01523aa7-f336-40c7-af6b-256dd19aacda)|![pos2](https://github.com/breez/breezmobile/assets/1225438/1bbd8919-d572-4b75-a599-552451df8cd1)|![pos1](htt …
> Add bulgarian language 💪 🇧🇬🇪🇺🇦🇱🇨🇿🇭🇺🇲🇩🇷🇴🇷🇺🇷🇸🇹🇷🇺🇦 🚀

- android/app/build.gradle
- ios/Runner/Info.plist
- lib/routes/home/account_page.dart
The date filter is not showing when we filter using date in the account page.
> fix issue where date filter not showing

- lib/routes/create_invoice/create_invoice_page.dart
This issue fixes an issue where users scanning or tapping an lnulw qr code with BTC selected as denomination/ currency is formated as sats and not BTC due to a race condition where we emit the `accountModel.initial()` on startup.
> don't build on accountmodel.initial

- lib/routes/account_required_actions.dart
- lib/routes/withdraw_funds/sweep_all_coins_confirmation.dart
- lib/routes/withdraw_funds/unexpected_funds.dart
- lib/routes/withdraw_funds/withdraw_funds_page.dart
- lib/utils/stream_builder_extensions.dart
- lib/widgets/home/home_app_bar.dart
- pubspec.lock
- pubspec.yaml
Adding logs for warnings and unexpected funds.
Also making two additional changes:
- extracting the nested StreamBuilder into a StreamBuilder5
- we had the StramBuilder2 already so I added the 3, 4, 5 and 6
- Extracting the Layout tooltip to breeze translations.
- Close your channel
- Wait for the Unexpected funds warning
- The unexpected funds flow should work as expected
|Closing channel|Unexpected funds|
|:-:|:-:|
|<video src="https://github.com/breez/breezmobile/assets/1225438/788df3b3-29ca-4f11-bc3f-ebabd097ac1b" />|<video src="https://github.com/breez/breezmobile/assets/1225438/f7a177ec-cdc2-4f56-b15a-430fd4a1934c" />|
> Add logs for warnings and unexpected funds

- lib/routes/charge/pos_invoice.dart
- lib/routes/podcast/transport_controls.dart
- pubspec.lock
- pubspec.yaml
This PR addresses
- https://github.com/breez/breezmobile/issues/1287
- Force dark brightness on system nav bar on POS page bd64088f24921e1978c09fdae94cbb398545df9b
> Force dark brightness on system nav bar on POS page

- lib/bloc/lnurl/lnurl_bloc.dart
- lib/handlers/received_invoice_notification.dart
- lib/routes/charge/pos_invoice.dart
- lib/routes/podcast/transport_controls.dart
- pubspec.lock
- pubspec.yaml
This PR addresses 
- #1286
- Remove redundant `isLightningAddress` check for clipboard item on `listenLNUrl` 0fa706dc539de8e1e13997d714348c8a90a650bc
- Don't check if account is connected or not before displaying payment request dialog edab5e4f98d7d4ce2535ef98fcafecaebbf1ed3d
- Wrap `_listenPaymentRequests` handler with `try/catch` block 62de82df2f99f8a01badeaf43b0cf144a9eb611c
- Reset `_handlingRequest` on error 97f4ccb9c8e8db6d4a9df45781f34c869a2f7a4d
> Clipboard issues

- ios/Podfile.lock
- lib/home_page.dart
- lib/routes/initial_walkthrough/dialogs/beta_warning_dialog.dart
- lib/routes/initial_walkthrough/dialogs/restore_dialog.dart
- lib/routes/initial_walkthrough/dialogs/select_backup_provider_dialog.dart
- lib/routes/initial_walkthrough/dialogs/widgets/snapshot_info_tile.dart
- lib/routes/initial_walkthrough/initial_walkthrough.dart
- lib/routes/podcast/theme.dart
- lib/routes/security_pin/remote_server_auth/remote_server_auth.dart
- lib/widgets/designsystem/button/action_button.dart
- lib/widgets/error_dialog.dart
- lib/widgets/single_button_bottom_bar.dart
- pubspec.lock
- pubspec.yaml
This PR forces blue theme on all restore flow UI's.
- Updates `Breez-Translations` depenency to address a typo on pending close channel estimation texts reported on #1278
> Address theme issues on initial walkthrough / restore flow

- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/bloc/user_profile/profile_animal.dart
- lib/bloc/user_profile/profile_color.dart
- lib/routes/security_pin/security_and_backup/security_tiles/pin_interval_tile.dart
- pubspec.lock
- pubspec.yaml
This PR addresses the issue where some Android manufacturers treat country code as language code for Czechia and l10n end up failing to map translations properly.
Depends on 
- https://github.com/breez/Breez-Translations/pull/38/
- Updated dependencies to latest
- Added additional comments on maximum compatible versions
> Fallback to Czech translations for deprecated language code "cz"

- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_content_title.dart
- lib/routes/home/widgets/payments_list/dialog/payment_details_dialog_description.dart
> Do not display subtitle if it's the same with title on payment details dialog
