breez/breezmobile

android/app/libs/breez.aar, lib/bloc/account/account_bloc.dart, lib/services/breezlib/breez_bridge.dart, pubspec.yaml
This PR handles reconnecting the account when needed according to the mobile lifecycle and network events.
More specifically a reconnection is attempted whenever:
1. The app resumed (enter foreground state)
2. The network changes to either wifi or mobile
3. On disconnection.
These attempts are buffered so we won't send redundant reconnects and every reconnect request is executed only if:
1. The account is currently disconnected
2. The network state allows it (mobile or wifi)
=> reconnect on foregraound, network changes and disconnections.

android/app/build.gradle, android/build.gradle, pubspec.yaml
- build.gradle: suppress warnings by using the 'implementation' directive
- pubspec: don't use git versions od firebase plugins
- Bump google-services to 4.2.0
- build.gradle: don't hardcode dependencies
=> Pubspec and gradle improvements

android/app/libs/breez.aar, lib/bloc/connect_pay/connect_pay_bloc.dart, lib/bloc/connect_pay/connect_pay_model.dart, lib/bloc/connect_pay/encryption.dart, lib/bloc/connect_pay/firebase_session_channel.dart, lib/bloc/connect_pay/online_status_updater.dart, lib/bloc/connect_pay/payee_session.dart, lib/bloc/connect_pay/payer_session.dart, lib/main.dart, lib/routes/user/connect_to_pay/connect_to_pay_page.dart, lib/routes/user/connect_to_pay/connected_peer.dart, lib/routes/user/connect_to_pay/payer_session_widget.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbjson.dart
This PR totally refactor the connect to pay mechanism to meet the following requirements:
- Session is now persistent and re-entrant, both payee/payer can enter the session multiple time using a session link. Both are recognized as corresponding payee/payer.
- Entering an existing session means it is reseted to the initial state.
- Both parties hold internally the same session identifier so the system will be able to notify them when other party entered a session.
=> Reenter session

android/app/src/main/java/com/breez/client/BreezFirebaseMessagingService.java, android/app/src/main/java/com/breez/client/job/JobManager.java, android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java, lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/user/home/wallet_dashboard.dart, lib/services/breezlib/breez_bridge.dart
This PR changes the "sync job" that should download the compact filters to be triggered from FCM rather than WorkManager.
The main reason is that the best practice should consider FCM trigger as first option to sync.
Currently we also cancels the job trigger to observe the FCM trigger behavior on different devices.
=> FCM based sync

lib/bloc/account/account_model.dart, lib/routes/user/connect_to_pay/payment_details_form.dart, lib/routes/user/create_invoice/create_invoice_page.dart, lib/routes/user/pay_nearby/pay_nearby_page.dart, lib/routes/user/withdraw_funds/send_coins_dialog.dart, lib/routes/user/withdraw_funds/withdraw_funds_page.dart, lib/widgets/amount_form_field.dart, lib/widgets/payment_request_dialog.dart
This PR add proper validation error in the cases of sent/request payments.
It takes into account the 1% channel reservation and all the logic for this validation is moved into the account model so it can be used not only from form fields.
=> Add 1% channel reserve proper explanation

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/pos/home/pos_invoice.dart, lib/routes/shared/initial_walkthrough.dart, lib/routes/user/home/wallet_dashboard.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/lnd_bootstrapper.dart
In this PR we consolidate the restore/initial start flows to show progressing indicator as long as the client didn't finish its bootstrap phase.
This PR also define better the bootstrap phase as the time range between the first startup and the first connection establishment with the routing node.
As long as the user haven't cross that line (the first connect) the app state will be "bootstrapping" and the progress indicator will be shown (regardless of its settings).
The above behavior applies for both fresh node and restored node.
=> Restore progress

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/shared/dev/dev.dart, lib/services/breez_server/generated/breez.pb.dart, lib/services/breez_server/generated/breez.pbenum.dart, lib/services/breez_server/generated/breez.pbgrpc.dart, lib/services/breez_server/generated/breez.pbjson.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbenum.dart, lib/services/breezlib/data/rpc.pbjson.dart, pubspec.yaml
This PR adds an internal feature to be able to disable/re-enable breez account.
When the account turns into "disabled" state, not automatic attempts to open a channel will be made.
This is useful when the user wants to close all his channels and withdraw the funds on-chain.
Later, he can re-enable the account and the attempts to open a channel will resume.
Since this is internal feature it is visible in the dev screen.
=> Disable account

lib/bloc/account/account_model.dart, lib/routes/shared/account_required_actions.dart, lib/routes/user/add_funds/add_funds_page.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbjson.dart, lib/user_app.dart
This PR is the final step for using the channel reserve in add funds.
Two changes here:
1. Only start the submarine swap process after account has finished bootstrapping.
2. Show proper error message when account is bootstrapping.
=> Add funds reserve

lib/routes/user/create_invoice/create_invoice_page.dart, lib/routes/user/home/account_page.dart, lib/routes/user/received_invoice_notification.dart
This commit fixes a bug that when receiving payment the code, from some reason, attempted to pop two routes from the route stack. The fix is to ensure we only pop until the home screen.
=> bug: Fix black screen when receiving payment.

lib/bloc/account/account_actions.dart, lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/user/received_invoice_notification.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbjson.dart
This PR adjusts the UI to the new FailedRoutes information that is added the PaymentResponse.
In the case of a payment error that is received from the router, we now send a response that contains this error and a trace routes report to send for further diagnostic (if the user accepts).
=> Trace routes bug report

lib/bloc/invoice/invoice_bloc.dart
This PR adds support for bip21 with bolt11 invoice: https://github.com/lncm/ideas/wiki/BIP21-w-BOLT11-wallet-support.
The format contains an embedded invoice so we only need to recognize it is bip21 format and extract the lightning invoice.
=> support bip21 with bolt11 invoice

lib/routes/pos/home/pos_invoice.dart, lib/routes/user/add_funds/address_widget.dart, lib/routes/user/create_invoice/qr_code_dialog.dart, lib/widgets/compact_qr_image.dart
This PR add an adjustment to the way we render a QR image by selecting the version dynamically.
The version ranges from 1 - 40 and reflects the number of modules (black and white dots) used to render the image.
We used this table (https://www.qrcode.com/en/about/version.html) to select dynamically the version according to the data length.
=> Compact QR Image

lib/bloc/invoice/invoice_bloc.dart, lib/utils/bip21.dart, test/invoice_test.dart
This PR takes a better (more robust) approach for parsing bip21 URI's and extract the optional bolt11 invoice embedded there.
The bip (https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) states that these URIs follow the general format for URIs as set forth in RFC 3986 so based on that the code was changes to use Uri.parse builtin in dart to get the query params and specifically the bolt11 we are interested in.
In addition, some unit tests were added based on feedback for the previous implementation.
Thanks @meeDamian.
=> Better approach for parsing bip21 URIs.

lib/bloc/account/account_actions.dart, lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/user/pay_nearby/pay_nearby_complete.dart, lib/routes/user/received_invoice_notification.dart, lib/widgets/payment_confirmation_dialog.dart, lib/widgets/payment_request_dialog.dart, lib/widgets/payment_request_info_dialog.dart, lib/widgets/processsing_payment_dialog.dart
This PR makes sure we safely dismiss the payment dialog when the payment is completed/cancelled/failed.
Safely means that we don't just pop out of the stack the last route but remove explicitly the route we need.
This is to prevent from other routes (like backup dialog) that we don't directly control from the flow, from being popped by mistake.
In addition the specific controller that was dealing with send payment requests is now removed and the actions going through the generic user action controller.
=> Safe dismiss payment dialog

lib/bloc/account/account_model.dart, lib/routes/shared/account_required_actions.dart, lib/routes/shared/funds_over_limit_dialog.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbenum.dart, lib/services/breezlib/data/rpc.pbjson.dart
This PR follows the PR in breez library (https://github.com/breez/breez/pull/74) and make the changes necessary to show proper statuses regarding the submarine swap process.
Specifically it shows warning icon on these cases:
1. Transaction amount is too small.
2. Transaction amount is over the limit.
3. Transaction amount and invoice provided contains different amount (probably when user executes another transaction to the address after the invoice was issued).
4. Transaction time lock has expired.
5. There is at least one transaction that won't be executed and the user can redeem his refund ( could be even due to unknown reason).
In addition when the funds are confirmed and the server side of the swap pays we show visual indication ( spinning progress ) on the top right corner.
=> Better show swap funds errors.

lib/routes/user/add_funds/fastbitcoins_page.dart
Fastbitcoins qr codes contain full url and with this PR we are reducing the scanned url to the voucher code. [BU-165](https://breeztech.atlassian.net/browse/BU-165)
=> Only take voucher code of the url being scanned on Redeem Fastbitcoins Voucher form.

lib/widgets/navigation_drawer.dart
This PR solves [BU-168](https://breeztech.atlassian.net/browse/BU-168)
If opening an expandable menu item stretches beyond visible content, the navigation drawer will scroll to bottom.
=> Scroll to bottom of visible content after opening an expandable item

android/app/src/main/java/com/breez/client/MainActivity.java, android/app/src/main/java/com/breez/client/NfcHandler.java
Foreground dispatch was blocking the client from paying the POS while the app is in the foreground. We only ever used it for writing to the Breez card, methods for which have also been removed.
=> NFC: remove foreground dispatch and methods for writing to Breez card

lib/bloc/account/account_model.dart, lib/bloc/connect_pay/payee_session.dart, lib/bloc/connect_pay/payer_session.dart, lib/routes/user/connect_to_pay/payee_session_widget.dart, lib/routes/user/sync_ui_handler.dart
This PR improves the connect to pay experience by fixing several issues:
1. Showing "Please wait while breez is synchronizng..." for payee when breez is still synchronizing before allowing him accept/reject payments.
2. Enforcing only one payment for payer session and only one payment request is generated for payee session. This is to prevent edge cases for accidentally paying more than once in one session. 
3. Fix syncUI auto removal to take into consideration cases where it is not on top of the stack.
=> Connect to pay fixes.

lib/routes/shared/security_pin/change_pin_code.dart
This PR fixes [BU-172](https://breeztech.atlassian.net/browse/BU-172).
Label is reset to "Enter your new PIN" if pin's does not match.
=> Reset label to Enter your new PIN if pin's does not match

lib/routes/shared/security_pin/lock_screen.dart, lib/widgets/pin_code_widget.dart
This PR fixes [BU-171](https://breeztech.atlassian.net/browse/BU-171).
Last digit's color fill animation is waited using Future's, before validation logic.
=> Wait for color fill animation to end before validating pin

lib/routes/shared/security_pin/security_pin_page.dart
In this PR we automatically triggers backup in the following cases:
1. When the `secureBackupWithPin` settings changes.
3. When the `secureBackupWithPin` is true and the pin activation/deactivation changes.
This way we ensure that the current backed up snapshot is consistent with the current user settings.
=> Trigger backup when pin code settings changes.

lib/routes/shared/security_pin/change_pin_code.dart, lib/routes/shared/security_pin/lock_screen.dart, lib/routes/shared/security_pin/security_pin_page.dart
As we have several variations of rendering the pin widget.
The variation that is rendered as AppLockScreen doesn't include a back menu item as user shouldn't be able to bypass that screen, so we ensure to disable the android back button as well at this case.
=> Allow back from pin only when back menu is shown.

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/AppDelegate.swift, ios/Runner/main.swift, lib/widgets/amount_form_field.dart
This PR sets the user locale to en_US in order to prevent iOS keyboard from showing locale specific decimal separator. 
The different decimal separator didn't pass the current code validator as described by this issue https://github.com/breez/breezmobile/issues/142.
As Flutter maintain its own Internalization mechanism (separated from the OS) and considering that iOS allows a wide range of locale customization, an attempt to solve the number formatting by taking into consideration different locales would be too risky and requires a big effort which is not the scope of this issue.
Closes #142
=> Temporary force number formatting in US locale only

lib/routes/user/home/home_page.dart, lib/user_app.dart, lib/widgets/barcode_scanner_placeholder.dart, pubspec.yaml
This PR addresses issue [#143](https://github.com/breez/breezmobile/issues/143).
If camera is not authorized* we route to BarcodeScannerPlaceholder page, which is similar in design to BarcodeScanner plugin. Users can use Paste Invoice feature and go to app settings to enable camera if they desire by clicking the information text.
*: Takes into consideration of the initial state where camera authorization hasn't been prompted yet.
Packages introduced:
- [permission_handler](https://pub.dev/packages/permission_handler)
=> Pay Invoice flow when camera has not been unauthorized

lib/bloc/invoice/invoice_bloc.dart, lib/routes/user/home/home_page.dart, lib/routes/user/home/invoice_bottom_sheet.dart, lib/routes/user/received_invoice_notification.dart, lib/widgets/barcode_scanner_placeholder.dart
This PR addresses [BU-181](https://breeztech.atlassian.net/browse/BU-181?utm_medium=referral-external&utm_source=jira-slack&utm_term=)
Flushbar with "Lightning Invoice wasn’t detected." is shown on invalid qr scans and clipboard items using BarcodeScanner plugin and it's placeholder.
This PR also adds error handling to Invoice Bottom Sheet's Pay button which got overlooked in #146
=> Show error on invalid scan/clipboard items.

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_synchronizer.dart, lib/routes/shared/dev/dev.dart, lib/services/breezlib/breez_bridge.dart
This PR enables the user to force a rescan from the wallet's birthday.
It is useful as a recovery mechanism when the ongoing rescan missed one of the blocks relevant to the user's transactions.
Such case may happen due to a bug or unknown reason and In that case the balance associated with some addresses  (including submarine swap addresses) won't be correct. 
In order to recover from such cases, we added this UI option.
When the user chooses this option, he will be required to restart the app for this to take effect where on the next restart breez will synchronize from its birthday given the opportunity to go over the missing blocks.
=> Force rescan

lib/routes/shared/account_required_actions.dart
When a refund is executed on some set of UTXOs the transaction enters the mempool but the amount associated with the address is still positive and in status confirmed.
Until confirmation we treat the address as still refundable and show it on the refundable list.
Since we don't want the refund warning icon to stay visible at this case we filter those refundable addresses to only contain those that there were no refund transaction associated with them in the past.
=> Only show refund warning in case refund wasn't executed for a specific address

lib/bloc/user_profile/security_model.dart, lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/shared/security_pin/change_pin_code.dart, lib/routes/shared/security_pin/lock_screen.dart, lib/routes/shared/security_pin/restore_pin.dart, lib/routes/shared/security_pin/security_pin_page.dart, lib/user_app.dart, lib/widgets/pin_code_widget.dart
In this PR we change the way we validate and update the pin code saved in the keychain.
Previously, the pin code was loaded to memory, kept in the UserModel as part of the SecurityModel. When user entered his pin code we validated it by comparing the key in the model with the entered key.
This change removes this field from the SecurityModel and eliminate the need to keep the value in memory. Instead, the Validation/Update actions were created and called on demand.
This approach should be more secure and less vulnerable to unexpected bugs.
=> Only fetch pin code on demand.

android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java, lib/bloc/account/account_actions.dart, lib/bloc/account/account_bloc.dart, lib/routes/shared/no_connection_dialog.dart
This PR enables the user to restore the chain information and start the chain bootstrap process from the beginning.
It is introduced as a recovery mechanism when neutrino files are corrupted from some reason.
The impact of this action is a couple of minutes in a bootstrap process during the next restart.
=> Reset chain info

lib/bloc/backup/backup_bloc.dart, lib/routes/shared/account_required_actions.dart
This PR add stream events to the backup bloc in case the backup dialog visibility changes.
Since this is a global dialog that is shown on top of the current context, it enables the current context be aware of it and take some necessary actions if needed. One example for such action is the webview that needs to change its own visibility.
=> Emit stream events when backup dialog visibility changes.

lib/pos_app.dart, lib/routes/pos/home/pos_home_page.dart, lib/routes/shared/account_required_actions.dart, lib/routes/user/home/home_page.dart
This PR ensure the backup dialog won't show up on top of the pin code widget.
=> Don't show backup dialog when pin is shown.

ios/Plugins/Breez/BreezLib/NativeMethods.swift, lib/routes/shared/network/network.dart, lib/services/breezlib/breez_bridge.dart, lib/widgets/animated_loader_dialog.dart
This PR uses a new breez API to ensure that the user supplied node supports bip157.
It adds a "processing..." dialog for several seconds and only allow to change the configuration if the test passes.
=> Test user node before applying changes.

ios/Plugins/Breez/BreezLib/Breez.swift, ios/Plugins/Breez/BreezLib/NativeMethods.swift, lib/bloc/backup/backup_bloc.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/user/get_refund/wait_broadcast_dialog.dart, lib/services/breezlib/breez_bridge.dart, lib/utils/crypto.dart, pubspec.yaml
This PR follows: https://github.com/breez/breez/pull/90 and move the responsibility for the generating the backup encryption raw keys and the encryption type itself from the breez library to  to the flutter app.
This enables the app to support generation of keys from different sources and enable later to implement the mnemonics source.
=> Prepare mnemonics

lib/routes/user/home/home_page.dart, lib/theme_data.dart, lib/user_app.dart
This PR fixes status bar color issue described on https://github.com/breez/breezmobile/issues/194
Both themes use white colored status bar icon and text instead of the previous black value.
=> Change status bar icon and text color to white

lib/bloc/account/account_model.dart
=> Fix RangeError when removing "Bitrefill" from payment descriptions

lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/shared/initial_walkthrough.dart, lib/routes/shared/security_pin/security_pin_page.dart
This issue addresses [BU-208](https://breeztech.atlassian.net/browse/BU-208).
SecurityModel was being reverted to it's original state before proceeding to register, which caused  fingertip menu to not show up on fresh installs unless users restarted or resumed the app.
enrolledBiometrics is now updated before processing register requests.
=> Do not reset enrolledBiometrics before proceeding to register

lib/bloc/account/add_funds_bloc.dart
This PR addresses [BU-214](https://breeztech.atlassian.net/browse/BU-214).
Users can now add any of their bank accounts that can make SEPA payments as a payment method using MoonPay.
=> Enable SEPA bank transfer payment method for MoonPay

lib/routes/user/add_funds/address_widget.dart, lib/theme_data.dart
The border around the QR image displayed in deposit address is removed.
=> Remove border around deposit address QR image

lib/routes/shared/security_pin/change_pin_code.dart, lib/routes/shared/security_pin/lock_screen.dart, lib/routes/shared/security_pin/restore_pin.dart, lib/widgets/circular_button.dart, lib/widgets/pin_code_widget.dart
This PR addresses issue  https://github.com/breez/breezmobile/issues/183.
The rectangular buttons are replaced with circular buttons that cover a larger area, previous shape caused some hits not to register.
=> Change shape of numpad buttons

lib/bloc/account/account_bloc.dart, lib/bloc/user_profile/security_model.dart, lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/shared/security_pin/security_pin_page.dart, lib/widgets/pin_code_widget.dart
We retrieve enrolled biometrics on device on demand rather than once every start up and each on resume. This reduces load on computing overhead and ensures we have the latest information.
enrolledBiometrics is removed from SecurityModel and is now being updated on onResume, on UI level.
=> Get enrolled biometrics on device on demand

lib/bloc/invoice/invoice_bloc.dart, lib/routes/shared/dev/dev.dart, lib/routes/user/add_funds/address_widget.dart, lib/routes/user/add_funds/conditional_deposit.dart, lib/routes/user/create_invoice/qr_code_dialog.dart, lib/routes/user/get_refund/wait_broadcast_dialog.dart, lib/routes/user/home/floating_actions_bar.dart, lib/routes/user/home/home_page.dart, lib/routes/user/withdraw_funds/swap_in_progress.dart, lib/services/device.dart, lib/widgets/payment_details_dialog.dart
This PR makes sure the "Paste Invoice" menu item ( and bottom bar action) is enabled only if there is a lightning invoice in the clipboard.
In order to achieve that I needed to make sure we have a synchronized stream of clipboard invoice and enable/disable according to the stream status.
=> Clipboard invoice

README.md, lib/bloc/user_profile/currency.dart
This PR addresses [BU-218](https://breeztech.atlassian.net/browse/BU-218).
- Users currency selection fallbacks to Sat on an unidentified symbol.
- Bit currency is removed from currency list.
=> Remove "Bit" currency

lib/bloc/app_blocs.dart, lib/bloc/invoice/actions.dart, lib/bloc/invoice/invoice_bloc.dart, lib/bloc/user_profile/currency.dart, lib/routes/charge/pos_invoice.dart, lib/widgets/pos_payment_dialog.dart
Moved https://github.com/breez/breezmobile/pull/132 into this branch. (_because I messed up resolving conflicts and wanted to save time rather than resolve it on that branch_)
- Add fiat currencies to the dropdown list
- Show decimals depending on `currencyData.fractionSize`
- Convert to last used bitcoin unit and display on the charge button
- Refactor duplicate code into `updateAmountControllers` and `clearCurrentAmounts`
- Recognize "sats" as Sat currency using Currency.fromSymbol().
=> POS: Add fiat support 

lib/routes/add_funds/address_widget.dart, lib/routes/create_invoice/qr_code_dialog.dart, lib/widgets/compact_qr_image.dart, lib/widgets/pos_payment_dialog.dart
This PR addresses [POS-25](https://breeztech.atlassian.net/browse/POS-25)
QR Image is given a white background across the app.
Cancel Payment button style now matches other cancel buttons on Dark mode.
=> QR image visual changes in dark mode

lib/routes/charge/pos_invoice.dart
This PR addresses regressions caused by #273
Regressions
- Disable charge button when entering invoice note.
- Do not convert currencies when flipping fiat vice versa.
- Show currency conversion of entered fiat amount on Charge button
Fixes
- Change 'SAT' to 'SATS' in the Charge [POS-28](https://breeztech.atlassian.net/browse/POS-28)
- Dark theme settings are applied to pos buttons.
=> Pos consolidation regressions

lib/routes/charge/pos_invoice.dart
This PR addresses [POS-34](https://breeztech.atlassian.net/browse/POS-34)
Switching currencies clears the current input and charge amount is converted.
`accountModel.fiatConversionList.firstWhere((f) => f.currencyData.shortName == value)` is used when converting from fiat -> fiat and sat -> fiat because of the delay in `userProfileBloc.fiatConversionSink.add(value);` to be reflected to the account model.
=> POS Currency conversion

lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/widgets/breez_avatar.dart, lib/widgets/breez_avatar_dialog.dart
This PR addresses [POS-38](https://breeztech.atlassian.net/browse/POS-38).
- Choosing a picture often doesn’t work
- Out of scope. 
This is the error related to this problem: ”gRPC Error (8, /breez.Pos/UploadLogo is rejected by ratelimit, please retry later.)”
- Choosing a custom picture causing the circle to look elliptic 
- Set an aspect ratio of 1:1
- When you choose a picture and cancel, when you open a again, the cancelled data remains in the dialog
- Profile picture now uploads to server when the user saves, not after selecting the image from gallery
- We need to add loader when choosing a custom picture
- This is not needed anymore as we pass the preview images bytes directly to BreezAvatar
=> Avatar picker bug

lib/widgets/breez_avatar_dialog.dart
This PR addresses [POS-43](https://breeztech.atlassian.net/browse/POS-43)
```
userBloc.userPreviewStream.listen((user) {
_nameInputController.text = user.name;
_currentSettings = user;
});
```
Setting `_nameInputController.text = user.name;` through this stream resets the value of username once the image upload completes, so it was removed and was being read once initially.
This caused a regression as Random button used this stream to set the new username.
We reverted the stream to it's initial state and we are using a temporary variable userName to update the name field.
We also disable changes to TextField during upload.
=> [Regression][Random button] Avatar Picker

lib/bloc/account/add_funds_bloc.dart, lib/bloc/account/fiat_conversion.dart, lib/bloc/user_profile/currency.dart, lib/routes/add_funds/deposit_to_btc_address_page.dart, lib/routes/charge/items/catalog_item.dart, lib/routes/charge/items/create_item.dart, lib/routes/charge/items/item_avatar.dart, lib/routes/charge/pos_invoice.dart, lib/routes/create_invoice/create_invoice_page.dart, lib/routes/home/payment_item.dart, lib/routes/transactions/pos_payment_item.dart, lib/routes/withdraw_funds/reverse_swap_page.dart, lib/routes/withdraw_funds/unexpected_funds.dart, lib/theme_data.dart, lib/widgets/currency_converter_dialog.dart
This PR follows up on #289 and addresses the feedbacks given in  [POS-48](https://breeztech.atlassian.net/browse/POS-48)
**Dashboard:**
- Remove the 'Add Note' (till the minimize task)
- Move the switcher button under the Charge button and add captions 'Keypad | Items'. Take the entire row, align to center. Make it behave like two buttons (only click on the inactive view switches view).
**Catalog View:**
- “No items to display. Add items to this view using the '+' button.”
- Remove the current amount (right to the switcher) in catalog view
- Use a regular icon for an item (as a reference)
**Slidable:**
- No need for the ‘Delete’ caption, icon is enough
- Background color of the slide should be the same as a button color. Foreground color should be white.
**Create Item Page:**
- Change the …
=> POS Items View - UI Fixes

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/bloc/user_profile/breez_user_model.dart, lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/charge/pos_invoice.dart, lib/routes/charge/sale_view.dart, lib/routes/transactions/pos_payment_item.dart
This PR addresses [POS-45](https://breeztech.atlassian.net/browse/POS-45).
Selected currency now persist :
- between user and pos mode,
- and after restarts*
*: Unless the app fails to retrieve exchange rates, which in that case the UI renders with BTC. 
If the user does not change to another currency at this point, the stored value for selected currency does not change. Meaning, restarting the app again and getting exchange rates without an error would display the selected currency.
=> POS currency persistence

lib/routes/charge/pos_invoice.dart, lib/routes/charge/pos_payment_dialog.dart, lib/routes/create_invoice/qr_code_dialog.dart, lib/widgets/pos_payment_dialog.dart
This PR addresses [POS-67](https://breeztech.atlassian.net/browse/POS-67)
"Scan the QR code to process this payment." text is replaced with "Scan to Process Payment" and moved to dialog's title.
Total charge amount is displayed in last selected currency(BTC/SAT) above QR image. If a fiat currency is selected, it's displayed right next to it in parenthesis.
=> Display total charge amount on pos payment dialog

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/routes/charge/pos_invoice.dart, lib/routes/charge/pos_payment_dialog.dart, lib/routes/sync_progress_dialog.dart, lib/widgets/circular_progress.dart
This PR fixes the sync progress dialog to refer to the daemon status as well.
If the daemon is not ready the sync progress shows a progress indicator with "Waiting for network" text.
The serverStatus flag is now populated in AccountModel.
In addition the waiting for sync handling in the POS flow is now moved outside (and before) the payment dialog.
=> Wait for sync when server is not ready

lib/bloc/account/account_actions.dart, lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/bloc/invoice/invoice_bloc.dart, lib/home_page.dart, lib/routes/home/account_page.dart, lib/routes/home/floating_actions_bar.dart, lib/routes/spontaneous_payment/spontaneous_payment_page.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbenum.dart, lib/services/breezlib/data/rpc.pbjson.dart, lib/utils/node_id.dart, lib/widgets/collapsible_list_item.dart, lib/widgets/payment_request_dialog.dart, lib/widgets/processsing_payment_dialog.dart
This PR allows a user to send spontaneous payments to those nodes that are configured to accept such payments.
Spontaneous payments do not require a payment request and only a node ID is needed.
Breez detects automatically the node id in the clipboard and user can paste it via the bottom sheet (of Send action) or the left menu.
Once pasted the "Spontaneous Payment" view is shown.
=> Support spontaneous payment

lib/routes/home/account_page.dart, lib/routes/home/wallet_dashboard.dart
This PR addresses [BU-228](https://breeztech.atlassian.net/browse/BU-228).
- Balance title is removed from wallet dashboard.
- Fiat equivalent of balance is shown under balance and users can switch between fiat currencies by clicking on this field.
- This field is only shown if the amount is bigger than minimal value, e.g. "< $0.01"
- Clicking on the fiat value will look up the next fiat currency that's above minimal value.
=> Add fiat value instead of balance

android/app/src/main/java/com/breez/client/NfcHandler.java, lib/services/nfc.dart, pubspec.yaml
Our previous solution, [flutter_nfc_plugin](https://pub.dev/packages/flutter_nfc_plugin) is the only plugin that you could check for app startup intent data. We later realized that it is only supported on Android.
We decided to handle the startup intent data natively and use a plugin that supports both iOS and Android for listening NFC stream while the app is open.
=> Use cross-platform plugin for nfc stream

lib/routes/charge/pos_invoice.dart
Using toInt() truncates the value retrieved from (currentAmount * normalizeFactor) which results in precision loss as any fractional digits are discarded.
=> Handle precision loss during type conversion 

lib/routes/charge/pos_invoice.dart
This PR fixes the regression that happened after moving note field to sale view.
The description data for invoices created during this regression are set as empty and they are not _recoverable_.
The invoice now uses the note field from sale view correctly.
=> [Regression] Set invoice description to current sale's note

pubspec.yaml
This PR addresses #361 
[Plugin Changes](https://github.com/breez/flutter_downloader/commit/9e570dfc4cbd4295c3e9e4f760ee49c79cb395e6)
- Plugins local notifications are removed from iOS.
=> flutter_downloader plugin notifications

lib/routes/home/account_page.dart, lib/routes/home/payment_item.dart, lib/routes/home/payments_list.dart
This PR addresses [BU-256](https://breeztech.atlassian.net/browse/BU-256)
I couldn't reproduce the bug on any physical or virtual device so we decided to go with this workaround where the avatar fades away as it's leaving the viewport.
- Title, amount text and bottom divider fades away too.
Concerns: Using Opacity is costly, we may revert to using this trick for avatar only if performance issues arises for our users. I had the same frame rate while scrolling on my tests with and without this workaround.
=> Payment list flashing bug

lib/routes/home/payments_filter.dart
This PR addresses UI bugs listed below related to payment sliver.
- Selecting and removing a date filter sets the filter to "All Activities" visually.
- Bottom border is missing when filter is set to Sent and Received.
------
- Date filter does not revert filter name to "All Activities" visually and now reflects the correct filter type.
- Bottom border is added to Sent and Received when there's no date filter active.
=> Filter sliver bugs

lib/bloc/account/fiat_conversion.dart, lib/bloc/user_profile/currency.dart, lib/routes/charge/currency_wrapper.dart, lib/routes/charge/sale_view.dart, lib/services/currency_data.dart, src/json/currencies.json
- Add position variable to currencies for symbol placement.
- Make distinction between displayName and currencySymbol on format method.
- If there are two currency texts with opposite text directions next to each other, use text-direction aware CurrencyText wrapped in CurrencyDisplay.
- Users can now scroll overflowing currency text on Sale View thanks to CurrencyDisplay.
=> Currency text direction support

lib/routes/home/payment_item.dart, lib/widgets/payment_details_dialog.dart, lib/widgets/payment_request_info_dialog.dart
This PR addresses [BU-269](https://breeztech.atlassian.net/browse/BU-269)
Previously description fields on payment request and payment details dialog had a maximum line property, which cropped description if it was longer than 3 lines. Now those are replaced with a scrollable area that shows 10, 3 lines at a time respectively showing the full description without cropping.
Transaction titles with new lines was producing an unwanted look, new lines on this field is now replaced with space character.
=> Multiline field support

lib/routes/connect_to_pay/payment_details_form.dart
This PR addresses [BU-270](https://breeztech.atlassian.net/browse/BU-270)
Submit button is invisible or cut off on devices with small screens on payer session. 
- Payment details form is wrapped with a scroll view to be able to scroll and click submit button for smaller devices or when keyboard is visible. 
- The columns' maximum axis size is set to minimum to keep the existing behavior for devices that has the available space.
=> Wrap payment details form with SingleChildScrollView

lib/home_page.dart, lib/routes/podcast/podcast_page.dart, lib/routes/podcast/theme.dart, lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart, lib/routes/security_pin/backup_phrase/generate_backup_phrase_page.dart, lib/routes/security_pin/security_pin_page.dart, lib/user_app.dart
Transformed withPodcastTheme to a wrapping widget for theme wrapping.
- Applied our dialog theme to podcast theme.
- Added overridePodcastTheme variable to override podcast theme for child widgets, which is used on pages under Preferences and their children.
=> Podcast theme regression

lib/bloc/podcast_payments/payment_options.dart, lib/bloc/podcast_payments/podcast_payments_bloc.dart, lib/bloc/user_profile/breez_user_model.dart, lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/home/bottom_actions_bar.dart, lib/routes/podcast/add_funds_message.dart, lib/routes/podcast/boost.dart, lib/routes/podcast/payment_adjuster.dart, lib/routes/podcast/payment_adjustment.dart, lib/routes/podcast/podcast_page.dart, lib/user_app.dart
This PR addresses [BU-285](https://breeztech.atlassian.net/browse/BU-285) and it's subtask [BU-296](https://breeztech.atlassian.net/browse/BU-296)
When the user has low balance, we display a message on top of player controls with a call to action button for users to add funds to their wallet. Pressing this button opens receive options much like on Balance modes, home page. _The routes to these options are now rendered with breez theme._
- Sats per minute and boost amount intervals are moved to PaymentOptions.
- Users podcast payment preferences now persist between different app sessions.
=> Show add funds message on low balance

lib/routes/home/account_page.dart, lib/routes/home/wallet_dashboard.dart, lib/theme_data.dart
This PR addresses [BU-303](https://breeztech.atlassian.net/browse/BU-303).
- Balance area's height has increased,
- Balance texts now use bolder & bigger fonts,
- Currency text is emphasized as clickable element on home page,
- Payment item's title uses a bolder font.
=> Home screen revamp

lib/bloc/podcast_payments/payment_options.dart, lib/bloc/podcast_payments/podcast_payments_bloc.dart, lib/bloc/user_profile/breez_user_model.dart, lib/bloc/user_profile/user_actions.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/podcast/boost.dart, lib/routes/podcast/custom_amount_dialog.dart, lib/routes/podcast/payment_adjuster.dart, lib/routes/podcast/payment_adjustment.dart, lib/routes/podcast/podcast_page.dart, lib/theme_data.dart
This PR addresses [BU-323](https://breeztech.atlassian.net/browse/BU-323)
Clicking on the boost or sats/min amounts will open a input dialog for users to enter a custom amount.
- The custom amount can’t be lower than minimum preset value (but can be higher than preset max value).
- The custom amount will be embedded into amount list.
- To remove custom amounts, users will need to enter an existing amount from preset values
- Added information text to tutorials to introduce this behavior.
- Grouped user preferences and custom amount under PaymentOptions,
- Removed unnecessary streams and related parameters on children widgets BoostWidget, PaymentAdjuster
=> Add ability to add custom boost & sats per min amounts

conf/marketplace.conf
The logo `ln.pizza_logo_lg.png` was misstyped as `lnpizza_logo_lg.png` on `conf/marketplace.conf` file.
how it looks like before and after the fix:
|Before|After|
|---|---|
|![photo_2021-06-08 15 02 53](https://user-images.githubusercontent.com/1225438/121236266-23f1bb80-c86c-11eb-8793-23950c26689b.jpeg)|![photo_2021-06-08 15 02 51](https://user-images.githubusercontent.com/1225438/121236285-281dd900-c86c-11eb-9da3-230ee3502972.jpeg)|
=> Fix ln pizza asset on apps page

test/utils/currency_formatter_test.dart
Increases the coverage from 54% to 90%
The line `FormatException` is never called because of the check `if (lowerBip21.startsWith("bitcoin:")) {` that causes `Uri.parse` to create a `_SimpleUri`, the exception is thrown on special cases when Uri.parse try to parse a `http` or `file:` uri but because of the check it never happens.
I just get the output and set as expected on the tests but I'm not sure if `'0'` is correct instead of `'0.00'` or `'12 345 678.9'` instead of `'12,345,678.90'`
=> Add tests for lib/utils files

lib/main.dart, lib/routes/home/payment_item.dart, lib/utils/date.dart, pubspec.yaml, test/utils/date_test.dart
@kingonly shares an idea with me about changing the time format shown on the home payments timeline.
The idea is to use relative time notation such as "1 day ago" to recent date (3 days or less) or "month/day/year" to older dates instead of just "month/day".
How those changes looks like:
https://user-images.githubusercontent.com/1225438/122615129-60889880-d05e-11eb-8b4b-645804078bd0.mp4
https://user-images.githubusercontent.com/1225438/122615137-64b4b600-d05e-11eb-8f9f-c56afb96e5c3.mp4
- The library that generates those messages is: https://pub.dev/packages/timeago
- The messages are customisable but for now it is using the defaults for english
- The library supports Spanish and other languages so it is compatible with https://github.com/breez/breezmobile/pull/464
=> Change payment timeline date format

lib/home_page.dart, lib/routes/security_pin/lock_screen.dart, lib/widgets/close_popup.dart
The idea is to fix the issue https://github.com/breez/breezmobile/issues/461 some context https://github.com/breez/breezmobile/pull/502
When you touch the back button, if the drawer is open the app should close the drawer instead of showing the exit dialog, in another hand if the drawer is already closed it should show the close dialog.
P.S. I had to change the `canCancel` from `Future` to a `Function` to correct execute its body after the back action, it seems to not affect the lock screen.
https://user-images.githubusercontent.com/1225438/122985838-072dab80-d375-11eb-9316-47b598d1a4c0.mp4
=> Close the drawer when back is pressed instead of showing the close dialog

lib/widgets/close_popup.dart
I was wondering the reason why the app closes abruptly instead of the smooth close that apps usually do. I find out the reason is the direct call to `exit` instead of calling `SystemNavigator.pop`.
This PR changes the close method, I could not record the animation it does now because the frame rate of the screen recorder is not enough to capture the animation, but as you run it you can notice the difference.
https://user-images.githubusercontent.com/1225438/123309180-fa3ac480-d4fa-11eb-9966-075f0fc8a708.mp4
=> Uses system navigator pop instead of calling exit directly

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/bloc/invoice/invoice_bloc.dart, lib/bloc/lnurl/lnurl_actions.dart, lib/bloc/lnurl/lnurl_bloc.dart, lib/bloc/lnurl/lnurl_model.dart, lib/handlers/lnurl_handler.dart, lib/home_page.dart, lib/lnurl_success_action_dialog.dart, lib/routes/home/account_page.dart, lib/routes/home/payments_list.dart, lib/routes/lnurl_fetch_invoice_page.dart, lib/services/breezlib/breez_bridge.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbenum.dart, lib/services/breezlib/data/rpc.pbgrpc.dart, lib/services/breezlib/data/rpc.pbjson.dart, lib/widgets/breez_avatar.dart, lib/widgets/error_dialog.dart, lib/widgets/payment_details_dialog.dart
This PR depends on [PR #135](https://github.com/breez/breez/pull/135).
This PR is ready for testing. Bugs and missing functionality are listed below.
- Fix: BreezMobile uses qr_code_tools. Upstream [qr_code_tools needs to upgrade its zxing dependency](https://github.com/AifeiI/qr_code_tools/pull/9).
=> LNURL-Pay.

lib/home_page.dart
Solves #528
Security & Backup page is now protected by Manager password.
User will be prompted manager password followed by PIN code if available before entering Security & Backup page _on POS mode_. 
- This behavior is exclusive to POS mode as switching to other modes requires the user to enter the Manager password beforehand.
=> Protect Security & Backup page with Manager Password

lib/routes/podcast/custom_amount_dialog.dart
On my device the dialog was not being shown, as you see on the following video:
https://user-images.githubusercontent.com/1225438/126834508-fb5886a3-38d6-4454-8a46-ea19dad64b85.mp4
It seems to be a issue with `AutoSizeText` as title to `AlertDialog`, because the text is always `"Enter a Custom Amount:"` I guess just changing it to `Text` is enough as you can see on the following video:
https://user-images.githubusercontent.com/1225438/126834662-7bdbb554-32e6-42a7-87df-65ad13dee022.mp4
If I'm missing something and it is necessary to use the `AutoSizeText` let me know so I can check the library code and try to solve that issue there.
=> Fix custom amount dialog

lib/home_page.dart
I have been working on some issues of the project on the last weeks and I had some problems figuring out what is happening on home page's build method because it was big and much of the code was too close to the right border making it crushed on the last columns of the text editor.
I did invest this morning breaking the method into some methods so we get the code closer to the left side and smaller methods making it easy to understand what is going on.
I tried to not change any code style or logic despite some changes were inevitable.
Please take a look and share your thoughts,  I don't want to make any radical changes on the project, I just believe this little refactoring will make much easier futures improvements on home page 🙏
=> Break home page build method into several methods

lib/routes/podcast/custom_amount_dialog.dart, lib/widgets/amount_form_field.dart, lib/widgets/sat_amount_form_field_formatter.dart, test/widgets/sat_amount_form_field_formatter_test.dart
I did move the `SatAmountFormFieldFormatter` to its own file to be reused on the custom amount dialog.
https://user-images.githubusercontent.com/1225438/126835359-664afc25-5910-48d6-8144-985d50195dd4.mp4
https://user-images.githubusercontent.com/1225438/126835197-cabdbe16-ae06-4d77-ae50-3b587d5d363a.mp4
=> Uses satoshi field formatter on custom amount dialog

lib/bloc/account/account_model.dart, lib/bloc/invoice/invoice_bloc.dart, lib/bloc/lnurl/lnurl_bloc.dart, lib/routes/home/bottom_actions_bar.dart, lib/routes/lnurl_fetch_invoice_page.dart, lib/widgets/enter_payment_info_dialog.dart, lib/widgets/payment_details_dialog.dart
This PR depends on https://github.com/breez/breez/pull/141.
- ~Silent fail if we've set an LNUrlResponseError.~
- This will be improved because Breez should present the user with an error if 
- they manually paste a non-lightning-address. -
- they paste a lightning-address but the host server generates an error.
---
```
$ curl -LR https://coinos.io/.well-known/lnurlp/chiron
LNURL payments temporarily disabled due to a server issue. Sep. 2, 2021. Join our Telegram channel https://t.me/coinoswallet for updates
```
=> Bug fixes and small changes to lightning-address functionality.

lib/bloc/podcast_payments/payment_options.dart, lib/bloc/user_profile/currency.dart, lib/routes/podcast/boost.dart, lib/routes/podcast/boost_message_dialog.dart, lib/routes/podcast/custom_amount_dialog.dart, lib/routes/podcast/custom_amount_form.dart
The main change of the PR is to add on boostagram dialog a form to set a custom amount.
The amount field is the same being used on other amount dialogs, to do so I had to extract the form to its own widget `CustomAmountFormField`.
Those changes also swap the tap and long-press behaviors, so now the tap opens the boostagram dialog and long-press applies the boostagram with the current value.
https://user-images.githubusercontent.com/1225438/133261138-b7ce6dbd-8d3d-46c3-b6c9-218c7b7e5056.mp4
=> Add custom amount to boostagram

lib/utils/date.dart
|Portuguese|English|Englis US|
|---|---|---|
|![portuguese](https://user-images.githubusercontent.com/1225438/139256875-8bf1242b-0b8e-4d68-9167-272df51b984e.png)|![english](https://user-images.githubusercontent.com/1225438/139256878-9351afb1-a10a-4684-af93-eb491fffa172.png)|![english_us](https://user-images.githubusercontent.com/1225438/139256883-87b9c022-02fe-4ea7-85d5-3edb40edb000.png)|
I'm adding Brazilian Portuguese only because it is the only Portuguese variant supported by the timeago
=> Add Portuguese support on timeago messages

lib/bloc/account/fiat_conversion.dart, lib/l10n/locales.dart, lib/services/currency_data.dart, lib/utils/locale.dart, src/json/currencies.json
|Default `x,xx €`|English `€x,xx`|Dutch `€ x,xx`|Turkish `€x,xx`|
|![pt](https://user-images.githubusercontent.com/1225438/139481694-6e1fe69d-f606-4c58-980a-a7f410094967.png)|![en](https://user-images.githubusercontent.com/1225438/139481688-612096f4-f8e6-4da3-a786-9d15004f8b65.png)|![nl](https://user-images.githubusercontent.com/1225438/139481678-f7e1dc63-909c-41ed-a0a4-7bc9309b8ff3.png)|![tr](https://user-images.githubusercontent.com/1225438/139481692-d331b1b6-3fe5-46f8-abc5-5801a1eead66.png)|
|Greek `x,xx €`| Cyprus's Greek `€x,xx`|German `x,xx €`|Austria's German `€ x,xx`|
|![el](https://user-images.githubusercontent.com/1225438/139481685-dc260dab-24b5-4f11-8fed-01e5d5ff3cba.png)|![el-cy](https://user-images.githubusercontent.com/1225438/139481690-9e1 …
=> Add locale support for currency format

lib/bloc/invoice/invoice_bloc.dart, lib/bloc/lnurl/lnurl_bloc.dart, lib/routes/home/qr_action_button.dart, lib/utils/lnurl.dart, lib/widgets/enter_payment_info_dialog.dart
Fixes: breez/breezmobile/issues/616.
=> Handle lightning-address URIs.

android/app/build.gradle, android/build.gradle, android/gradle.properties, pubspec.yaml
- app_settings: `4.1.0` -> `4.1.1`
- archive: `3.1.2` -> `3.1.6`
- confetti: `0.5.5` -> `0.6.0`
- connectivity: `3.0.3` -> `3.0.6`
- duration: `3.0.6` -> `3.0.8`
- flutter_secure_storage: `4.2.0` -> `4.2.1`
- flutter_web_browser: `0.14.0` -> `0.15.0`
- grpc: `3.0.0` -> `3.0.2`
- image: `3.0.2` -> `3.0.8`
- image_cropper: `1.4.0` -> `1.4.1`
- logging: `1.0.1` -> `1.0.2`
- package_info: `2.0.0` -> `2.0.2`
- qr_code_scanner: `0.4.0` -> `0.6.1`
- sqflite: `2.0.0+3` -> `2.0.0+4`
- sqflite_common_ffi: `2.0.0+1` -> `2.1.0`
- tutorial_coach_mark: `1.0.0` -> `1.1.1`
- webdav_client: `1.0.0` -> `1.1.2`
- build_runner: `2.0.4` -> `2.1.2`
- drag_and_drop_lists: `0.3.2` -> `0.3.2+1`
- path_provider: `2.0.1` -> `2.0.4`
- printing: `5.2.1` -> `5.5.0`
- shared_preferences: `2.0.6` -> `2.0.7`
- …
=> Update flutter dependencies

android/app/build.gradle, android/build.gradle, android/gradle.properties
- junit / junit-kotlin
- test-runner
- espresso
- kotlin-stdlib: Starting from Kotlin 1.4.0, the stdlib dependency is added automatically, so no need to declare it
- legacy-support-v4: There is no need to support sdk 4 as the minimum sdk is 24
- work-runtime: `2.3.4` -> `2.6.0`: There is a version `2.7.0` but it depends of compile sdk 31
- lifecycle-process: `2.2.0` -> `2.3.0`: There is a version `2.4.0` but it depends of compile sdk 31
- gifimageview: There is a version `2.2.0` but it is not working with the Jetifier
- appcompat: `1.0.0-beta01` -> `1.3.1`
- exifinterface: `1.0.0-beta01` -> `1.3.3`
- material: `1.0.0-beta01` -> `1.4.0`
- biometric: `1.0.0` -> `1.1.0`
- play-services-auth: `16.0.1` -> `19.2.0`
- play-services-drive: `16.0.0` -> `17.0.0`
- google-api-client-android: …
=> Update android dependencies

lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fi.arb, lib/l10n/app_pt.arb, lib/routes/charge/pos_invoice.dart, lib/widgets/view_switch.dart
The idea is to re-use this component in a new screen being developed, to do it I had not only to extract but I had to make the spacing dynamic to work properly given the length of texts. I had to make the icons optional too.
How it looks like in different languages:
|KeyPad|Items|
|---|---|
|![after_en_1](https://user-images.githubusercontent.com/1225438/145051807-15814f0d-fe17-470b-acb0-10acca9417e4.png)|![after_en_2](https://user-images.githubusercontent.com/1225438/145051639-82513af6-efba-400d-90ab-a5f0f0c37635.png)|
|![after_pt_1](https://user-images.githubusercontent.com/1225438/145051648-8f9f590b-389f-49bd-bfa5-f907d27f0dfa.png)|![after_pt_2](https://user-images.githubusercontent.com/1225438/145051810-2c215943-2dfb-47df-866c-36be8f47937e.png)| …
=> Extract view switch component and make it dynamic

lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fi.arb, lib/l10n/app_pt.arb, lib/routes/charge/items/item_avatar_picker.dart, lib/routes/charge/items/item_page.dart
|En / Fi|Pt / Es|
|---|---|
|![en](https://user-images.githubusercontent.com/1225438/146936078-f45b176b-5615-46c4-943d-49d6753c14a0.png)|![pt](https://user-images.githubusercontent.com/1225438/146936089-7e016320-c9b1-4180-9d3e-6fb07427e82f.png)|
|![fi](https://user-images.githubusercontent.com/1225438/146936087-9756364a-9ba4-499c-b046-2ac59d3d4db0.png)|![es](https://user-images.githubusercontent.com/1225438/146936084-c8df2489-4170-4e64-b4e0-5a7222823737.png)|
=> Add translations to POS item image picker

lib/routes/charge/pos_invoice.dart, lib/routes/charge/pos_invoice_num_pad.dart
POS page has some issues on small screens, this PR fixes them.
*notice I'm using split-screen to simulate smaller screens.
|Before|After|
|---|---|
|![before_1](https://user-images.githubusercontent.com/1225438/147127294-71ba0fb7-0a1e-4083-a92e-59ef1c6fc0c0.png)|![after_1](https://user-images.githubusercontent.com/1225438/147127282-a37b4152-d12a-440e-92ed-e732ac3ccca0.png)|
|![before_2](https://user-images.githubusercontent.com/1225438/147127296-2d16e04f-f9c8-4250-94b0-bb293815cb3b.png)|![after_2](https://user-images.githubusercontent.com/1225438/147127287-ecd08998-c217-40d0-b9d7-22348c60663f.png)|
|![before_3](https://user-images.githubusercontent.com/1225438/147127297-f9a7a4ef-344a-4a22-b728-3836f2f045b6.png)|![after_3](https://user-images.githubusercontent.com/1225438 …
=> Improve pos page on smaller screens

lib/routes/create_invoice/create_invoice_page.dart
Just increase the height to fix the text bounds
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/147482057-8cf23a58-43ff-4c2d-8202-4c2da282f6f2.png)|![after](https://user-images.githubusercontent.com/1225438/147482051-10195a4b-fcc1-4b61-a1ff-42d1f7b884d6.png)|
=> Increase warning box height

lib/routes/fiat_currencies/fiat_currency_settings.dart, lib/services/currency_data.dart, src/json/currencies.json
This PR is a proposal on how to display currencies on fiat currencies screen showing its native name plus a localized name if necessary.
Below are some examples, for instance, the US Dollar is showing as `US Dollar` in English and `US Dollar (Dólar Americano)` in Portuguese, the rationale behind this is to show the currency native name so it is easier to its user find it and inside the parenthesis, the name localized by the language of the device.
|English|Portuguese|Spanish|
|---|---|---|
|![en](https://user-images.githubusercontent.com/1225438/147507051-859b4673-0957-417e-8d1b-f34c738c2114.png)|![pt](https://user-images.githubusercontent.com/1225438/147507047-92368a5b-bdb5-45d5-b0db-2e8d1ef7cb9a.png)|![es](https://user-images.githubusercontent.com/1225438/147507050-662813b3-5d46-4907-8b7 …
=> Add translation to fiat currency names

lib/bloc/account/account_bloc.dart, lib/bloc/account/account_model.dart, lib/bloc/pos_catalog/repository.dart, lib/bloc/pos_catalog/sqlite/repository.dart
This PR is a purpose on how to fix the misidentified sale items.
e.g., on the following videos, you can see a Sale (first item +206 sats) and a Connect to Pay transaction (third item +100 sats).
Before these changes, because of the heuristics, both are shown in the list as a Sale Item, after the changes only the real Sale item is shown.
A bad side effect of these changes is the load that sometimes some transactions will show, on the videos I leave, and I back to the Balance page to show some items being loaded.
Please let me know your thoughts about this approach and the code, Happy new year 🥳 
https://user-images.githubusercontent.com/1225438/147827241-e8e49a9e-04b5-40a6-b59d-3e20d258fb5e.mp4
https://user-images.githubusercontent.com/1225438/147827263-23758db1-1675-4b58-b31a-c478b88e6b0f. …
=> Better identification of payment items

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/breez/client/NfcHandler.java, ios/Runner/Info.plist, lib/services/lightning_links.dart
Add deep link support for [Lud 17](https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md) links.
https://user-images.githubusercontent.com/1225438/150827676-c1b1111e-2811-46aa-8841-2007e7b191f9.mp4
Notice I did use the following HTML to make links clickable as the system does not recognize custom URL schemes properly
```
<html>
<head>
<title>Text Lud-17</title>
</head>
<body>
<p>
<a href="lnurlp://lnurl.fiatjaf.com/lnurl-pay?session=13bc050935c0dc15ba82e3c76296725656a3edaa01a113a9fd439611687f250d">lnurlp://lnurl.fiatjaf.com/lnurl-pay?session=13bc050935c0dc15ba82e3c76296725656a3edaa01a113a9fd439611687f250d</a>
</p>
<p>
<a href="lnurlw://lnurl.fiatjaf.com/lnurl-withdraw?session=854128f23d24a9a4b5d9a030db62b66543d23e8fb2509d18adfa254c318f4b32">lnurlw://lnurl.fiatjaf.com/lnur …
```
=> Add deep link support for LUD17 links

lib/routes/home/bottom_actions_bar.dart
Thank you @bitcoinuser for the error report 🙏 
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/151666497-039f45df-4955-4a93-909b-f3f5575840ae.png)|![after](https://user-images.githubusercontent.com/1225438/151666495-ab86fa49-06ce-4ec2-9a45-719bf837ba8f.png)|
=> Fix warning box text cut

lib/l10n/app_es.arb, lib/l10n/app_pt.arb, lib/services/breezlib/breez_bridge.dart
Fixes https://github.com/breez/breezmobile/issues/688
For some reason the camera scanner is sending the address as uppercase, I did add a `.toLowerCase()` to fix it,
Fixed a translation text too, the action should be in present mode "TRANSMITIR" instead of past mode "TRANSMITIDO/TRANSMITIDA".
=> Fix bitcoin uppercase coming from camera scanner

lib/utils/print_pdf.dart
"Transaction Time" text is the first item printed on POS receipts, then business title, then the tx time itself.
To correct this behavior transaction time is moved below business title.
=> Adjust transaction pdf layout to correct POS receipt layout error

pubspec.yaml
In order to advance on the reproducible build issue referred to https://github.com/breez/breezmobile/issues/247  and https://github.com/breez/breezmobile/issues/504 I'm replacing the ranges syntax `^x.y.z` by specific static version `"x.y.z"` on this updating.
The list of updated depedencies:
- app_settings: from `4.1.1` to `4.1.5`
- dio: from `4.0.4` to `4.0.6`
- extended_image: from `6.0.1` to `6.0.2+1`
- file_picker: from `4.5.0` to `4.5.1`
- image_cropper: from `1.5.0` to `1.5.1`
- image_picker: from `0.8.4` to `0.8.5`
- package_info_plus: from `1.4.0` to `1.4.2`
- webview_flutter: from `3.0.1` to `3.0.2`
- build_runner: from `2.1.7` to `2.1.8`
Notice some dependencies have been declared with a lower minor, but because of the ranges syntax, it was allowed to use a newer minor version …
=> Update flutter dependencies (patches increments)

android/app/build.gradle, pubspec.yaml
In order to advance on the reproducible build issue referred to https://github.com/breez/breezmobile/issues/247  and https://github.com/breez/breezmobile/issues/504 I'm replacing the ranges syntax `^x.y.z` by specific static version `"x.y.z"` on this updating.
The list of updated depedencies:
- firebase_core: from `1.14.0` to `1.15.0`
- firebase_database: from `9.0.8` to `9.0.12`
- firebase_dynamic_links: from `4.0.8` to `4.2.0`
- firebase_messaging: explicit `11.2.14`
- lifecycle-process: from `2.4.0` to `2.4.1`
- play-services-auth: from `20.0.1` to `20.1.0`
- firebase-bom: from `29.0.4` to `29.3.1`
=> Update firebase dependencies

lib/routes/security_pin/backup_phrase/enter_backup_phrase_page.dart
This PR addresses #897  
Restore backup phrase form was being reset upon changing pages. This caused a frustrating experience if the backup failed and users had to correct a word on previous page because they would need to enter all inputs from the start, rather than checking and correcting their existing input. 
Typeahead plugin is also updated to null safety, which caused errors on empty results. Suggestions now return an empty list rather than null to correct this behavior.
- Form is no longer reset upon changing pages.
- Fixed suggestion box behaviour on empty results.
=> Do no reset form after changing pages on restore backup phrase

android/app/src/main/java/com/breez/client/BreezFirebaseMessagingService.java, android/app/src/main/java/com/breez/client/plugins/breez/BreezShare.java, android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Notification.java
Not specifying mutability of PendingIntent's broke functionality for Android 12 devices due to[ this change](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability).
I've specified mutability of each PendingIntent we use.
=> Specify the mutability of PendingIntents for Android 12+

lib/routes/charge/pos_invoice.dart
Fixes #901 
On the POS keypad screen, the currency type drop-down was clearing the entered number after choosing the same currency from the drop-down.
This PR fixes it. Entered numbers are cleared only if the chosen currency is different.
=> fix dropdown clearing for pos screen

lib/bloc/payment_options/payment_options_bloc.dart
On a fresh first run, the default was a hardcoded true instead of the actual value stored in the proper constant, this commit fixes it.
=> Fix default value for override (link to default const value)

lib/bloc/user_profile/currency.dart, lib/routes/charge/sale_view.dart, lib/utils/print_pdf.dart
Apply the changes proposals from https://github.com/breez/breezmobile/issues/916
- Changes the satoshi symbol from `Ş` to `丰`
- Uses currency ticker (3 letters) instead of the currency symbol.
|Before|After|
|---|---|
|![before-1](https://user-images.githubusercontent.com/1225438/172475339-5c55fff3-1e98-4047-9b1d-87cabe39d2df.png)|![after-1](https://user-images.githubusercontent.com/1225438/172475346-71120abe-6f0f-4bab-82e8-1ba2af187feb.png)|
|![before-2](https://user-images.githubusercontent.com/1225438/172475341-baa7bdfc-71b0-4a57-a4f7-97a0e21f82f1.png)|![after-2](https://user-images.githubusercontent.com/1225438/172475343-8b0083b8-ac5c-4495-ac6e-c469b2817883.png)|
|![before-3](https://user-images.githubusercontent.com/1225438/172475334-b7e7ee85-49ba-42b7-9833-91ad4ab897e5.png)|![after-3 …
=> Change satoshi symbol and print currencies tickers instead of symbol

lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fi.arb, lib/l10n/app_fr.arb, lib/l10n/app_pt.arb, lib/routes/funds_over_limit_dialog.dart
- Added approximately_an_hour and approximate_hours texts to help with pre-formatting hoursToUnlock string and removed funds_over_limit_dialog_redeem_hour text. 
- funds_over_limit_dialog_redeem_hours now uses pre-formatted hoursToUnlock string.
=> funds_over_limit_dialog_redeem_hours localization improvements

lib/routes/qr_scan.dart, lib/widgets/scan_overlay.dart, pubspec.lock, pubspec.yaml
qr_code_scanner isn't working as expected after Flutter 3.0.x update, it requires going into Gallery and returning back to QR screen to start scanning. This is likely a render order/state management issue but I think this is a great opportunity to upgrade [qr_code_scanner](https://pub.dev/packages/qr_code_scanner) that's in maintenance only mode to [mobile_scanner](https://pub.dev/packages/mobile_scanner) by the same author.
- qr_code_scanner's underlying frameworks are no longer maintained,
- Replaced qr_code_scanner with mobile_scanner, that uses the latest version of MLKit for detecting barcodes and QR codes
- Created a ScanOverlay widget to match overlay behavior of qr_code_scanner
- Replaced helper methods with Widgets
=> Update QR code scanner plugin

lib/routes/podcast/transport_controls.dart
The recent changes on Anytime broken the alignment as the `SpeedSelectorWidget` changes its width depending on the speed selected, this PR fixes it. Solves https://github.com/breez/breez-issues/issues/7
|1x|2.25x|
|---|---|
|![1x](https://user-images.githubusercontent.com/1225438/183434011-d949772e-587f-44bf-ac6b-9357465f1066.png)|![2 25x](https://user-images.githubusercontent.com/1225438/183433997-a2a09661-5f72-486d-8d72-8fae902c3d4d.png)|
=> Fix player control alignment

lib/l10n/app_fi.arb
Myyntipiste (Sales Point) is not good Finnish. Maksupääte translates to Payment Terminal, which is commonly used term for devices with similar (eg card payment) functions.
=> Update app_fi.arp Maksupääte

lib/routes/qr_scan.dart
Bug reported here: https://t.me/breez_lightning/25654 
The bug happens when a valid QR code is read, but a previous QR code has already consumed and released the widget.
=> Fix crash when cam reads multiple QR codes

lib/bloc/reverse_swap/reverse_swap_model.dart, lib/l10n/app_en.arb, lib/routes/withdraw_funds/swap_in_progress.dart, lib/routes/withdraw_funds/tx_widget_with_info_message.dart, lib/services/breezlib/data/rpc.pb.dart, lib/services/breezlib/data/rpc.pbenum.dart, lib/services/breezlib/data/rpc.pbgrpc.dart, lib/services/breezlib/data/rpc.pbjson.dart, lib/widgets/payment_details_dialog.dart
This adds lockup transaction information when a user has sent an on chain transaction. 
Have updated the protocol buffer in since I added a new field to breez lib https://github.com/breez/breez/pull/165.  ⚙️ 
Pressing view transaction redirects me to the blockstream.info/tx/ 😃
=> 13 add locktx info

lib/bloc/podcast_payments/podcast_payments_bloc.dart
This change adds the PodcastIndex `itemID` to the podcast payment TLV records.
The `itemID` is very useful for podcasters and services on the receiving side to properly associate boosts with episodes, as the episode titles can sometimes change which is unreliable.
=> Add Episode Item ID to Podcast Payment TLV

lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fi.arb, lib/l10n/app_fr.arb, lib/l10n/app_it.arb, lib/l10n/app_pt.arb, lib/l10n/app_sv.arb, lib/routes/withdraw_funds/reverse_swap_page.dart, lib/utils/exceptions.dart, test/utils/exceptions_test.dart
Fix the reported bug [add-error-extraction-on-send-btc-flow
//github.com/breez/breezmobile/pull/new/add-error-extraction-on-send-btc-flow](https://t.me/breez_lightning/26414)
I couldn't test on an actual iOS device; the error message already comes without the messy part on Android.
How it looks like, (Not exactly the same error as reported as it is on Android):
=> Extract error message on send BTC flow

lib/routes/withdraw_funds/tx_widget_with_info_message.dart
This pr references a fix to displaying the lockup txID in #995 
Do we even need to display claim txID here ?
=> display txid first and not claimTxID

lib/bloc/reverse_swap/reverse_swap_bloc.dart, lib/bloc/reverse_swap/reverse_swap_model.dart, lib/routes/withdraw_funds/tx_widget_with_info_message.dart
References #1016 
This pr makes it possible to a user to send another onchain transaction once the lockTx is confirmed. 
Usually the user had to wait for the commitment transaction to confirm too.
=> remove wait for claimTxID

android/app/build.gradle, android/build.gradle, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fi.arb, lib/l10n/app_fr.arb, lib/l10n/app_it.arb, lib/l10n/app_pt.arb, lib/l10n/app_sv.arb, lib/routes/qr_scan.dart, pubspec.lock, pubspec.yaml
Scan lib was adding hms which contains a tracker, so I'm replacing it with mobile_scan https://github.com/flutter-package/flutter_scan/blob/main/android/build.gradle#L44 
As I was testing the scan flow, I also updated the lib.
As a bonus, as we are already using the mobile scanner, we are reducing the number of dependencies and the size of our app 🎉 
Scan made by the Classy Shark:
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/1225438/210801421-3c2f4c68-fd03-4381-a211-695c29678980.png)|![after](https://user-images.githubusercontent.com/1225438/210799266-be865a08-2255-4d1f-b02f-c9360b8cc775.png)|
=> Uses mobile scan instead of scan removing scan lib

lib/routes/network/network.dart
A regression on the network page was made by removing the divider after the tor switch
=> Add divider back to network page

lib/bloc/user_profile/backup_user_preferences.dart, lib/bloc/user_profile/breez_user_model.dart, lib/bloc/user_profile/user_profile_bloc.dart, lib/routes/initial_walkthrough.dart, lib/routes/splash_page.dart, lib/theme_data.dart
Changes in [update theme to dark after initial walkthrough](https://github.com/breez/breezmobile/commit/2a709589918b1540e5fda438f2907d1ef2cde1d8#diff-dc818ab51dfc8f9e518dee3af008fae6a792af8196eb38770bd71005b2608c47R371) 2a709589918b1540e5fda438f2907d1ef2cde1d8 introduced a regression with backup where the restored user model was not being used.
The proposed solution in that commit is implemented;
- Blue theme is forced on initial flow pages
- Wrapped topmost widget of their build() with Theme using blue theme.
- Default themeID is set to Dark,
- Restored user preferences are being used on restore again.
=> Dark theme - Backup regression

lib/bloc/account/account_bloc.dart, lib/bloc/backup/backup_bloc.dart, lib/bloc/tor/bloc.dart, lib/routes/security_pin/remote_server_auth.dart, lib/services/injector.dart
Earlier I changed the attempting url from `/remote.php/ in this f128ee6f5c59f775a18484488e7841868c17749a commit.
This creates a successful sign-in, but the app is not able to locate or upload backup files successfully. Though this is not good it does at least not cause any issues in regards to us having to maintain the `remote.php/dav` url.
The app will first try the url the user inserted, but it this does not work it will attempt to try connect to the shorturl + remote.php/webdav.
This pr depends on https://github.com/breez/breez/pull/182 
@erdemyerebasmaz  if you have an old instance can you help with testing with an old instance of nextcloud ?
=> Revert from /dav to /webdav and error better

lib/routes/home/payments_filter.dart, lib/routes/settings/pos_settings_page.dart, lib/routes/transactions/pos_transactions_page.dart
This PR addresses 
The CSV's were being created successfully but shareXFiles requires a XFile to be shared and there was regression because we were passing filePath to shareXFiles, which worked with deprecated shareFiles method. All other instances are checked and these were the only remnants.
We were also popping navigator stack at all times instead of checking if loader route is active and consequently removing it.
=> Export CSV issues

lib/bloc/account/account_bloc.dart
This pr is related to #1099 which happens when tor is active.
The cause of the issue was that tor is being activated before we gather account information. This can be deferred until before we start lighting which happens in __listenUserChanges_. 
As a result the initial loading seems to go faster.
=> defer tor initialisation

ios/Runner/Info.plist
We got a report from a user that scanning an NTAG 424 DNA card on iOS doesn't do anything on iOS. It looks like we're missing the select-identifier for these tags in the Info.plist file.
=> support in-app NTAG 4xx on iOS

.github/workflows/main.yml, .gitignore, android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, pubspec.lock, pubspec.yaml
Updated Android Gradle Plugin to resolve build issues from Android Studio up to latest Electric Eel version.
- Target Flutter 3.7.12 when building from CI
- Add Flutter.podspec to .gitignore
- Update dependencies to latest
- forked md5_file_checksum and made it compatible with bundled Kotlin version
- Update minSdkVersion to 28
- path_provider_android requirement
=> Upgrade AGP from version 7.1.3 to 7.4.2

lib/bloc/account/fiat_conversion.dart, lib/bloc/user_profile/currency.dart, lib/routes/charge/items/item_page.dart
This issue references #1111.  Which is a known issue on Samsung phones when using [`TextInputType.numberWithOptions`](https://github.com/flutter/flutter/issues/61175)
I have allowed for the use of either comma or dot in the `whitelistedPattern` function. 
We then proceed with replacing all commas with dots in order to adhere to the `double.parse` function. 
Are there another place in the app we wish to or should accepts comma too?
https://github.com/breez/breezmobile/assets/36157890/e160cbc4-a4c1-4418-a0a0-c28a4d1391a6
=> allow comma in POS mode #1111

lib/bloc/invoice/invoice_bloc.dart, lib/bloc/invoice/invoice_model.dart, lib/bloc/lsp/lsp_bloc.dart, lib/routes/create_invoice/create_invoice_page.dart, lib/routes/create_invoice/qr_code_dialog.dart, lib/routes/create_invoice/setup_fees_dialog.dart, pubspec.lock, pubspec.yaml
This PR addresses several issues one of which is where we're not able to create invoices ~1 hour after the app is opened, as LSPInformation is stale. Other is conveying the information that he setup fees has changed to the user in the rare occasion user spent ~1 hour in the Receive via Invoice page.
To address first issue:
- FetchLSPList action will list LSP's even if they've been already fetched.
Fees are fetched before creating each invoice. If there has been a change in fees, Setup fees dialog will be shown to the user before displaying the invoice dialog.
Added error handling & prevented clicking create invoice when an invoice is currently being created(rare case where fetching LSPInformation takes too long).
=> Check validity of Dynamic Fees when creating invoice

lib/routes/charge/pos_invoice.dart, lib/routes/connect_to_pay/payee_session_widget.dart, lib/routes/create_invoice/create_invoice_page.dart, lib/routes/home/bottom_actions_bar.dart, lib/widgets/single_button_bottom_bar.dart
This PR adds a loader indicator when LSP's are being refreshed, mainly for users with very slow networks.
- Push a loader route when lsp's are being refreshed
- Remove loader route on errors
- No longer disable create invoice button(as loader route will prevent clicks)
- Disable create invoice button when LSP isn't connected yet
=> Display a loader route when LSP's are being fetched

lib/utils/node_id.dart
This pr check if we are able to parse the given nodeID to hex in order to avoid parsing lighting addresses which can be the same length as nodeID.
=> check that nodeID can be parsed to hex

lib/bloc/invoice/invoice_bloc.dart, lib/routes/home/qr_action_button.dart, lib/widgets/enter_payment_info_dialog.dart
fixes #1126 
We now accept and handle bip 21 invoices in both the clipboard and enter payment info dialog. 
We will need to test this before build in either testpilot or the android apk since my emulator had some odd behaviour.
=> fix bip21 handling

lib/services/breezlib/breez_bridge.dart, lib/utils/bip21.dart, test/invoice_test.dart
This enables extracting bitcoin address from bip21 URI. 
Also introduces propperhandling for native segwit and legacy addresses if they are prefixed with **bitcoin:**.
=> check for bip21 on validating address

lib/routes/create_invoice/create_invoice_page.dart, lib/routes/lnurl_fetch_invoice_page.dart, pubspec.lock, pubspec.yaml
Fixes https://github.com/breez/breezmobile/issues/1162
Updated translations.
I did not find a way to make different parts of the string clickable so I used a textspan widget and split the text accordingly.
**Ps textstyle in video is wrong, but correct in commit**
https://github.com/breez/breezmobile/assets/36157890/031a123d-8879-4547-b8f5-f36bd0a94162
=> make lnurl clickable

lib/bloc/backup/backup_bloc.dart, lib/bloc/backup/backup_model.dart, lib/routes/initial_walkthrough/dialogs/widgets/snapshot_info_tile.dart
Latest backup time is stored in UTC and this can be confusing from the users perspective.
Latest backup time is converted to local time
- after restoring snapshot,
- when initializing `BackupState` from persistent data,
- When displaying snapshot list on `RestoreDialog`
=> Use local time for latest backup time

lib/bloc/backup/backup_actions.dart, lib/bloc/backup/backup_bloc.dart, lib/routes/initial_walkthrough/initial_walkthrough.dart
Previously, users were stuck with the Google account they signed into first on restore flow and it required a fresh install to sign in with another account.
Now we're calling sign out before provider selection dialog is shown*. This change allows users to switch Google accounts on restore. 
*: Only on restore flow, this does not affect provider selection dialog on Security & Backup settings.
=> Allow users to switch Google accounts on restore flow

lib/bloc/backup/backup_bloc.dart, lib/bloc/backup/backup_model.dart, lib/routes/account_required_actions.dart, lib/routes/funds_over_limit_dialog.dart, lib/routes/initial_walkthrough/dialogs/widgets/snapshot_info_tile.dart, lib/routes/lsp/select_lsp_page.dart, lib/user_app.dart, lib/widgets/enable_backup_dialog.dart, lib/widgets/home/home_app_bar.dart
This PR introduces changes in 
- #1121 
to 
- #1189
> Behavior changes:
> - Makes `promptBackupController` a behavior subject fixing https://github.com/breez/breezmobile/issues/1116
> - Add a `promptBackupDismissedStream` to avoid multiple prompts in the same session
> - Add a few logs to help bug reports
> - Makes `pushPrompt` take into account only `_enableBackupPrompt`
> - Makes `AccountRequiredActionsIndicator` reads its own blocs
> - Unify streams on `AccountRequiredActionsIndicator` using `combineLatestList`
>
=> Improve backup prompt logic & fix concurrency bugs

android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java, ios/Runner/Info.plist, lib/routes/security_pin/security_and_backup/backup_tiles/backup_provider_tile.dart
This PR addresses feedback & issues found from the latest review on 
- #1183
- Don't prompt sign in if request is silent
- This caused an issue on new accounts on Android where user got bombarded with sign in prompts, that is if they cancelled each one, wherever they were on the app.
- Do not recreate sign in client on calling getAccessToken
- Remove CloudKit from Info.plist [Waiting on TestFlight for confirmation]
- Remove obsolete OR condition
=> Address backup feedback

android/app/src/main/java/com/breez/client/plugins/breez/breezlib/Breez.java, android/app/src/main/java/com/breez/client/plugins/breez/breezlib/GoogleAuthenticator.java, ios/Plugins/Breez/BreezLib/Breez.swift, ios/Plugins/Breez/BreezLib/GoogleAuthenticator.swift, ios/Plugins/Breez/BreezLib/iCloudBackupProvider.swift, ios/Runner/Info.plist, lib/bloc/backup/backup_actions.dart, lib/bloc/backup/backup_bloc.dart, lib/bloc/backup/backup_model.dart, lib/routes/account_required_actions.dart, lib/routes/backup_in_progress_dialog.dart, lib/routes/initial_walkthrough/dialogs/restore_dialog.dart, lib/routes/initial_walkthrough/dialogs/select_backup_provider_dialog.dart, lib/routes/initial_walkthrough/initial_walkthrough.dart, lib/routes/security_pin/backup_phrase/verify_backup_phrase_page.dart, lib/routes/security_pin/remote_server_auth/remote_server_auth.dart, lib/routes/security_pin/security_and_backup/backup_tiles/backup_provider_tile.dart, lib/routes/security_pin/security_and_backup/backup_tiles/remote_server_credentials_tile.dart, lib/routes/security_pin/security_and_backup/security_and_backup_page.dart, lib/services/breezlib/breez_bridge.dart, lib/widgets/enable_backup_dialog.dart, lib/widgets/error_dialog.dart, pubspec.lock, pubspec.yaml, test/bloc/backup/backup_bloc_test.dart
This PR fixes many issues surrounding restore backup.
App was getting stuck on `"Restoring data..."` loader after entering a valid but incorrect mnemonic phrase because the error handler wasn't working as expected. 
There was likely a change in Dart which deprecated this syntax:
`.catchError(_restoreFinishedController.addError));`
This has been replaced with:
```
.catchError((error) {
_restoreFinishedController.addError(error);
}),
```
and it fails as expected and loader is popped.
---
The error message for incorrect mnemonic phrase which was illegible:
> FileSystemException: Failed to decode data using encoding 'utf-8', path = '/var/mobile/Containers/Data/Application/0866BE9F-3585-425F-B0D0-1013490F027C/Documents/app_data_backup/lightningFees.txt'
is now being replaced with:
> Failed to …
=> Refactor Initial Walkthrough restore flows

android/app/build.gradle
Add a debug config section so we can share a debug keystore to test google/firebase integrations functionalities
=> Add debug build config

ios/Runner/Info.plist, lib/routes/security_pin/security_and_backup/security_and_backup_page.dart, lib/widgets/enable_backup_dialog.dart
Received a support case where user ran into issues when going to the security and backup page with the current iOS app store version.
`BIND: Failed assertion: boolean expression must not be null
#0      SecurityAndBackupPageState.build.<anonymous closure>.<anonymous closure> (package:breez/routes/security_pin/security_and_backup/security_and_backup_page.dart:217)
#1      StreamBuilder.build (package:flutter/src/widgets/async.dart:444)
`
and 
`Failed assertion: boolean expression must not be null
#0      EnableBackupDialogState.build.<anonymous closure> (package:breez/widgets/enable_backup_dialog.dart:69)`
=> [support case]fix null issue

lib/widgets/payment_request_info_dialog.dart
=> use onPress to display fiat

lib/routes/transfer_funds_in_progress_dialog.dart
This PR addresses #1232
Instead of popping the last item on navigation stack, the route(dialog) itself is removed if it's active.
=> Transfer Funds in progress dialog state management

lib/bloc/lnurl/lnurl_model.dart, lib/routes/account_required_actions.dart
Encountered this issue when testing for https://github.com/breez/breezmobile/pull/1234 where every `WarningAction` uses the hardcoded `account_required_actions_backup` text, "Backup", as tooltip.
All warning actions have their respective tooltips with these changes.
=> Display the correct tooltip for warning actions

lib/handlers/check_version_handler.dart, pubspec.lock, pubspec.yaml
Related https://github.com/breez/breezmobile/issues/413
If the app is installed from Google Play, it opens Google Play as it is today, if the installation source is somewhere else, it opens the release page on GitHub
Also breaking the method into smaller methods and adding logs
https://github.com/breez/breezmobile/assets/1225438/788e24cf-33e1-48a9-b535-07a028dfcd5b
=> Check instalation source on Andriod and open github page instead of google play store if the instalation source is not google play

src/json/vendors.json
current link is not working 
let me know if a new referral link should be used, then I'll add it 
Or maybe the problem is at Azteco side
=> Apps: fix broken Azteco link

lib/services/breez_server/server.dart
Fixes issue where we haven't established an active channel to breez server before attempting to signin. This caused issues for users trying to open moonpay immediately after opening the app.
=> ensure valid channel before signin

lib/bloc/backup/backup_bloc.dart, lib/bloc/backup/backup_model.dart, lib/routes/security_pin/security_and_backup/backup_tiles/backup_provider_tile.dart, lib/routes/security_pin/security_and_backup/security_and_backup_page.dart, lib/widgets/enable_backup_dialog.dart
`backupProvider` may be null; so I'm adding a null check when accessing it.
=> Add null checks for backup provider

lib/bloc/podcast_payments/actions.dart, lib/bloc/podcast_payments/podcast_payments_bloc.dart, lib/main.dart, lib/routes/podcast/payment_adjustment.dart, lib/routes/podcast/podcast_loader.dart, pubspec.lock, pubspec.yaml
Reference: https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#value-time-split
Recommended reading: https://blog.getalby.com/value-time-split-the-latest-innovation-in-podcasting-2-0/#:~:text=Value%204%20Value%20is%20a,and%20cross%20referencing%20of%20content
- Search for a podcast episode with support to value time split
- e.g. https://breez.link/p?feedURL=https%3A%2F%2Fmp3s.nashownotes.com%2Fbballrss.xml
- Boost inside a time-split range
- The boost should be split according to the podcast receipts and the remote recipts
- Boost outside a time-split range
- The boost should be sent as a traditional boost
There is no change in UI so I'm attaching some logs to exemplify how the boost happens
- [outside-split.txt](https://github.com/breez/breezmobile/files/13488635/o …
=> Add value time split

lib/utils/date.dart
=> use en date format when locale not available 

android/app/src/main/java/com/breez/client/job/JobManager.java
An attempt to deduplicate sync jobs at the root level, namely where they're scheduled.
Tested with a firebase notification. The job is still triggered at least. I'm not sure whether it will actually be deduplicated.
=> schedule chain sync as unique work

lib/routes/podcast/transport_controls.dart, pubspec.lock, pubspec.yaml
This PR addresses
- #1281 
Loader is now displayed around Play/Pause button when buffering instead of replacing the play button.
https://github.com/breez/breezmobile/assets/4012752/8021e7e8-be74-4977-bb16-4fff793213de
=> Display loader around Play/Pause button when buffering

pubspec.lock, pubspec.yaml
Fixes #1275
This crash was fixed on `clipboard_watcher` v2.1.0 but v2.1.0 also made it incompatible with Flutter 3.7.12
Forked `clipboard_watcher` and excluded Dart 3/Flutter 3.10 upgrades. [breez/clipboard_watcher@3.7.12_npe_crash](https://github.com/breez/clipboard_watcher/tree/3.7.12_npe_crash)
=> Fixed a bug where a blob(non-text) item on clipboard would crash the app on Android

lib/main.dart, lib/routes/podcast/podcast_page.dart, pubspec.lock, pubspec.yaml
closes #583
>by default the player shows the podcast logo. When a chapter comes up with a dedicated picture, that podcast logo disappears, there is a split-second blue screen, and then the chapter picture fades in.
> Is that blue screen expected / necessary?
Blue placeholder is replaced with a transparent one.
> It seems to be better to fade out the podcast logo and directly fade in the chapter pic.
While this is possible, it requires a product decision and won't be addressed as part of this PR.
- [Use a transparent placeholder when switching chapter image](https://github.com/breez/breezmobile/commit/38551bb5fc5456635ca1e4954f96fd2ea53fb864)
Picked a Podcast with many chapters with different images in a short timeframe:
|Before|After|
|---|---|
|<video …
=> Use a transparent placeholder when transitioning Podcast chapter image

lib/routes/initial_walkthrough/dialogs/beta_warning_dialog.dart, lib/routes/security_pin/backup_phrase/backup_phrase_confirmation_page.dart, lib/widgets/enable_backup_dialog.dart, lib/widgets/payment_failed_report_dialog.dart
closes #242
Wrapped label with `GestureDetector` that changes checkbox value on tap.
https://github.com/breez/breezmobile/assets/4012752/129919a1-7b0e-430e-bd81-db81e916cd1d
=> Allow checking the checkbox by tapping on the corresponding label

lib/routes/charge/cart/cart_bar_drop_down_button.dart, lib/widgets/error_dialog.dart, pubspec.lock
This PR improves upon previous approach which was updating currency list and adding logs on each rebuild.
POS currency list is now populated 
- once on `initState` when the widget is built
- every time there's a change* on currency list
- *: removal/addition/reordering of preferred fiat currencies
=> Only update POS currency list if there's a change

android/app/build.gradle, ios/Podfile.lock, pubspec.lock, pubspec.yaml
App target API level has been updated to API level 34 to meet requirements of updated Google Play Store policies.
> From Aug 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.
- Updated dependencies to latest resolvable
=> Update app to target Android 14 (API level 34)

src/json/vendors.json
Changes made: Corrected the URL for the 'Sms4Sats' service from 'http://sms4sats.com/' to 'https://sms4sats.com/'. This ensures that the application uses a secure (HTTPS) connection when accessing the Sms4Sats API, which helps protect user data and maintain trust in the service.
=> "Update URL for Sms4Sats"

src/json/vendors.json
Changes made: Updated the key name from 'tbc' to 'TBC' in the configuration for The Bitcoin Company.
=> Update Key Name for The Bitcoin Company

android/app/src/main/java/com/breez/client/plugins/breez/Tor.java
The tor config failed to initialize with the following error:
```
[TorBloc] {INFO} (2024-12-02T18:52:43.172705Z) : TorBloc.startTor failed: PlatformException(error, com.breez.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.breez.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
at android.os.Parcel.createException(Parcel.java:3235)
at android.os.Parcel.readException(Parcel.java:3211)
at android.os.Parcel.readException(Parcel.java:3153)
at …
```
=> fix tor config receiver

.github/scripts/export-options.plist, .github/scripts/sign.sh, .github/workflows/main.yml, ios/Runner.xcodeproj/project.pbxproj
Apple no longer accepts bitcode in app submissions. This PR addresses this issue by stripping bitcode from `Tor.framework`.
It has several other improvements, such as updating deprecated methods & bringing the build steps in line with our new & updated CI workflows, and using GitHub actions w/ caching mechanism to save time on setting up Go, Flutter & checking-out SDK repository.
=> Update & optimize CI workflow for App Store Connect compatibility
